### PR TITLE
Add Setup Script To Install Section

### PR DESCRIPTION
**Pull request by adamisntdead**
0. [x] Project URL:
[here](https://github.com/adamisntdead/CleanMacSetup)

1. [x] Why should this project be added:
While I am the creator, it is a setup script mainly for web development that has worked for me many times
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
Also, target your suggestion to [this locations](https://github.com/iCHAIT/awesome-macOS#mac-dev-setup).

**Comment by herrbischoff** [comment]
> How is this better/different from this.

@iCHAIT: I'd say the difference is that one is a manual and the other one a collection of scripts to do it automatically. No objection from me to add it to the Mac Dev Setup category. Even if it's only for looking at bits and pieces how others set up their machines.

**Comment by iCHAIT** [comment]
Okay, so @adamisntdead just target this to the location I have mentioned in my previous comment and we'll merge.

**Comment by adamisntdead** [comment]
Thats it I think!

**Pull request merged**
