### PR TITLE
Adding Max to Audio section

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by bashu** [comment]
squashed

**Comment by herrbischoff** [comment]
The latest stable release of this software is from 2009. Even if most functionality may be included and it runs, this appears to be an awful long time of neglect.

**Comment by bashu** [comment]
fine, but it works for me...

**Comment by fedot** [comment]
Max is a great piece of software to have on the list. The fact that the release is from 2009 doesn't make it awful - it makes it stable.

BTW, unstable build is from 2011 and the development takes place on https://github.com/sbooth/Max (contributions welcome)

**Comment by dkhamsing** [comment]
@herrbischoff should we include this to the list?

**Comment by herrbischoff** [comment]
I'm still not convinced that this is a truly awesome addition.

**Pull request closed without merging**
