### PR TITLE
Add IINA

### PR DESCRIPTION
**Pull request by shreyasminocha**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://lhc70000.github.io/iina/
2. [x] Why should this project be added: It's a fully-featured media player with a great design
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by stackptr** [comment]
The link on the OSS icon should probably match the Github project link. Currently it points to the Wineskin project.

I vote for this inclusion after that change is made, I use IINA daily as a native alternative to VLC.

**Comment by herrbischoff** [comment]
Is it really stable enough yet? The last time I checked it was alpha quality software. Also the version number v0.0.14.1 does not inspire too much confidence in its stability.

**Comment by stackptr** [comment]
Yeah I guess I can't speak too much to its stability as I probably don't stress test it on a day to day basis. It's worth pointing out that IINA is basically a GUI wrapper around `mpv` which is going to be the bulk of the heavy lifting in terms of playing video. I checked out the Github project and there seems to be a decent amount of development and organization around the app. There are 375 open issues in the project, which means 36% of total issues are unresolved, but sorting by comments it doesn't appear there are tons of _critical_ bugs.

I wonder if there are other metrics that can give an idea of stability? Ultimately any one person's experience of the software is not going to be a great guide on that.

**Comment by shreyasminocha** [comment]
@stackptr Thanks for pointing out the thing about the OSS icon. It's been pretty stable in my experience as well, but again, we'll need to look for some objective measure of stability. [It's being developed actively for sure](//github.com/lhc70000/iina/pulse/monthly).

**Comment by iCHAIT** [comment]
LGTM 👍

**Pull request merged**
