### PR TITLE
Add Jiffy

### PR DESCRIPTION
**Pull request by sindresorhus**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://sindresorhus.com/jiffy
2. [x] Why should this project be added: GIFs!!
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
@sindresorhus Not to poop on the parade, but: Gify is now owned by Facebook and they use the GIFs provided basically as tracking pixels, provided their links are shared. How does your app deal with that? Apple and Signal have already taken measures against this form of tracking in their respective messenger apps. As this appears to be a closed source application I couldn't check the internals myself.

**Comment by sindresorhus** [comment]
Jiffy sends no identifiable information to GIPHY (not even a private tracking identifier they recommend). The IP is obviously shared, but there’s no way around that, and with IPv6, a new address is generated regularly.

**Comment by herrbischoff** [comment]
Thanks for your quick response. What do you mean by

> with IPv6, a new address is generated regularly

Does the application use a server component hosted by you? How would a new IPv6 address be generated otherwise?

**Comment by sindresorhus** [comment]
I’m not well-verses in IPv6 intricacies. I just remember reading something about this.


https://www.google.no/search?client=safari&hl=en-us&sxsrf=ALeKk02l46t6XxDaEu6o4yx_FfeRP1HiYQ%3A1591526343352&ei=x8PcXp2BFbvdmAXxnrqIAw&q=ipv6+privacy&oq=ipv6+privacy&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAMyBAgjECcyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAOgQIABBHOgYIABAWEB5QxERYtVFgj1VoAHABeACAAXiIAYoIkgEDMy43mAEAoAEB&sclient=mobile-gws-wiz-serp

**Comment by herrbischoff** [comment]
Interesting. I didn't know that. Going to research this "privacy mode" a little more.

This means I can assume your application establishes direct connections to Giphy and does **not** use a server-side proxy or the like, which is under your control?

**Pull request merged**
