### PR TITLE
Add crashplan backup application

### PR DESCRIPTION
**Pull request by forgottenleaf**

### CODE REVIEW

**Comment by forgottenleaf** [comment]
The failed tests are not due to my additions. Also, I removed the trailing whitespace on the entry for KeePassX.

**Comment by forgottenleaf** [comment]
I fixed the failed test in this (due to NepTunes) in PR #258.

**Comment by dkhamsing** [comment]
does anyone else have experience with this app

**Comment by dkhamsing** [comment]
We feel this change did not receive enough endorsement
Sorry 😢

**Comment by vassyz** [comment]
Might be too late, but I can highly recommend the app. I've been using it for over a year without any issues. Another competitor in the Backup category would be [Backblaze](https://www.backblaze.com/), but I went with CrashPlan because their app can backup straight from my NAS drive. I get unlimited backups for $6/month.

**Pull request closed without merging**
