### PR TITLE
Add Batch Image Resizer

### PR DESCRIPTION
**Pull request by brunowego**
Ref. #285

### CODE REVIEW

**Comment by dkhamsing** [comment]
@brunowego is this free?

**Comment by brunowego** [comment]
The site says nothing about license.

**Comment by dkhamsing** [comment]
@iCHAIT 
@herrbischoff 
should we add the free icon?

**Comment by iCHAIT** [comment]
I think its free, their site mentions -

> While this application is provided free of charge, you can support us by purchasing it on the Apple App Store for just $2. 

So I believe we can add freeware icon to it.

**Pull request merged**
