### PR TITLE
Additions, Deletions, Error Corrections

### PR DESCRIPTION
**Pull request by lizenas**
If you want me to say why each individual app should be added I will but in general they are all highly useful applications that showcase macOS's merits and/or extend it's features.

### CODE REVIEW

**Comment by lizenas** [comment]
The builds keep failing because wesnoth.org is timing out.

**Comment by iCHAIT** [comment]
Hi @lizenas 

Thank you for your PR :smile: , but please can you open a separate PR for each of your suggestions? Specially for the one's where you are adding/deleting an application, it would be easier for everyone  to review and discuss them in detail.

All the corrections  that you have suggested can go in a single PR :)

Thanks.

**Comment by iCHAIT** [comment]
Also before opening a separate PR for each addition that you suggest, can you please check if that application has already been rejected (from closed PR's)? As far as I remember apps like **VLC** and **Adium** have already been rejected.

**Comment by lizenas** [comment]
Oh alrighty, I'll do that in the morning.

**Pull request closed without merging**
