### PR TITLE
Add Deeplink Buddy

### PR DESCRIPTION
**Pull request by dqhieu**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://deeplinkbuddy.com
2. [x] Why should this project be added: Deeplink Buddy is a developer tool which helps me a lot in my job to manage deeplinks as a mobile engineer. As an engineer, I usually save all my deeplinks to Apple Notes, then whenever I want to run them, I have to copy and paste them to the terminal and run it. This takes many steps, and lots of them can be reduced. So this app helps you manage all deeplinks, and list out all available simulators so you can select the deeplink, then select the simulator, and press Run. Very simple and intuitive.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
Deeplink is usually a fancy word for bookmark. Okay, but what is a "deeplink" in this context? I'm guessing app development but it's entirely unclear. The website reads like a Ricky and Morty interdimensional cable episode about plumbuses. 

What does it DO?

**Comment by dqhieu** [comment]
Hi, deeplink is a type of link that send users directly to a screen in an app. This keyword is familiar to mobile engineers who implement deep linking in their apps. You can learn more about deeplink here: https://www.adjust.com/glossary/deep-linking/

I also have a demo of the app here

https://user-images.githubusercontent.com/8291457/213862204-37239905-326e-4796-8d56-6cfff53a1040.mp4

Hope this clarifies your concerns.

**Comment by herrbischoff** [comment]
Thanks, I will be looking into it when and if I find the time.For future submissions, may I suggest not assuming that anyone knows about your domain-specific lingo if you’re looking to get it included in a general outlet. On 21. Jan 2023, at 11:10, Hieu Dinh ***@***.***> wrote:﻿
Hi, deeplink is a type of link that send users directly to a screen in an app. This keyword is familiar to mobile engineers who implement deep linking in their apps. You can learn more about deeplink here: https://www.adjust.com/glossary/deep-linking/
I also have a demo of the app here
https://user-images.githubusercontent.com/8291457/213862204-37239905-326e-4796-8d56-6cfff53a1040.mp4
Hope this clarifies your concerns.

**Comment by dqhieu** [comment]
Noted with thanks.

**Comment by stackptr** [comment]
The description is not very helpful in understanding why or how this would be useful. Most apps in that section are "made by developers, for developers." After watching the example video, I'd describe something like:

> Deeplink Buddy - Save and run deeplinks in Simulator for developing and testing iOS apps

It seems like a very niche app, but I do not have experience in iOS development

**Review by dqhieu — COMMENTED** [review]
Update description

**Comment by dqhieu** [comment]
Thanks for the suggestion. I have updated the description for Deeplink Buddy

**Comment by iCHAIT** [comment]
@herrbischoff @stackptr fina thoughts on this?

**Comment by herrbischoff** [comment]
I don't think it fits particularly well on this list.

**Pull request closed without merging**
