### PR TITLE
Add Querious

### PR DESCRIPTION
**Pull request by mage3k**
0. [x] Project URL: https://www.araelium.com/querious/
1. [x] Why should this project be added: It is a mysql client with nice UI. 
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by dkhamsing** [comment]
In general, please open one pull request per project 

Iina was previously rejected because but it is in alpha

As for Querious,  can you tell us why we should add it to the list

**Comment by herrbischoff** [comment]
Please don't forget to add examples of where your pick beats the current listings and why that is relevant.

**Comment by herrbischoff** [comment]
Gotta love those drive-by committers…

**Comment by mage3k** [comment]
@herrbischoff I am not drive-by committer, thx.

**Comment by herrbischoff** [comment]
If you don't understand something that's perfectly alright. I, for one, wouldn't be able to understand a single word of Chinese. Please ask for clarification instead of just going away. However, I believe Google Translate should be able to sufficiently transfer the meaning of "add more information of why this application is awesome", especially if you were able to understand a rather unusual term like "drive-by committer".

**Comment by mage3k** [comment]
If I did not understand the wrong words, the drive-by committer were accusing me？

**Comment by ajnsit** [comment]
I can understand how it would be confusing to someone who's native language is not English. From the OP's perspective they already answered the question of why this app should be added. To quote - "It is a mysql client with nice UI".

I understand that this repo has a higher standard for accepting new entries (which is great), but it is not really obvious from the [contribution guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md).

Perhaps more details should be added to that document, detailing the requirement for endorsements, comparison with existing items in the same category etc. I would submit a PR for that myself, but it's probably better for the maintainers with write access to define.

**Comment by herrbischoff** [comment]
I don't see it as our responsibility to hand-hold everyone who happens to drop by. In this case, the fact that two applications were submitted in one pull request demonstrate that the OP clearly did *not* read the contribution guidelines. More elaborate wording wouldn't have made a difference because that document was simply ignored.

I think that if someone feels stating the obvious is enough of a description, this person is just being lazy, language barriers or not. This is a common sense issue. What happened to comparing former art (accepted pull requests) for pointers? Did not happen, as it would have been clear that IINA was already rejected (for the time being). Putting up the effort to write that you did not understand something? Did not happen. Instead, the pull request was just closed. No explanation.

So, no, I don't see that there's an issue with a language barrier that could have been prevented by adding more information to a document that keeps getting ignored.

@ajnsit, if you feel overhauling the contribution guideslines should nevertheless be discussed, you're more than welcome to open an issue (or even a new pull request) with your suggestions and the team will take a look. For now, I'm going to lock this conversation as the pull request is closed.

**Comment by iCHAIT** [comment]
@mage3k Not a problem, we all face such issues. Anyway, if you are still interested, feel free to open a new and a cleaner pull request for the same, **adding more information of why this application is awesome**  :)

**Pull request closed without merging**
