### PR TITLE
Add wallpaper changer

### PR DESCRIPTION
**Pull request by srishanbhattarai**
0. [x] Project URL: http://irvue.tumblr.com
1. [x] Why should this project be added: It is a simple, lightweight and easy to use wallpaper changer that delivers high quality images from Unplash.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
Personally, I don't care in the least about frequently changing my wallpaper, even less about doing it with a separate application. In my book, software like this is crapware and to be avoided at all costs.

**Comment by srishanbhattarai** [comment]
Isn't the reason why this is a list is so that people can pick and choose what they want to install? There are several apps already on the list I wouldn't want to install. 
I know a good number of colleagues and friends who use and prefer this application which is why I made a pull request.

**Comment by ajnsit** [comment]
I just tried it and this seems a really cool app. FOSS and also available on App Store for free. Thanks for the suggestion @srishanbhattarai !

**Comment by herrbischoff** [comment]
Surely I am entitled to my opinion that I voice when a pull request is opened. We're a team of several people and this is my view. Please note that this pull request was not closed but left open for discussion.

What you got wrong is that a suggestion entitles you to anything but your opinion. We discuss the merits of every application within the team and whether to add it or not. I wouldn't add it but that doesn't mean that @iCHAIT or @dkhamsing may see some value in it. Remember that this is an "Awesome" list. In my view a wallpaper changer application does not qualify.

**Comment by srishanbhattarai** [comment]
Noted. I apologize if I came out harsh.

Back to the point. - it's a high quality app which a good number of people would like IMO. Personally, I think it's pretty awesome 😄.  Try it out.

**Comment by iCHAIT** [comment]
@herrbischoff To be honest, I don't see why a wallpaper changer application does not qualify as an awesome application, I understand that it may not seem to be that intuitive or a necessary application that should exist on every Mac, but I have seen many people using such application just for the mere fun of it. I myself started using a [similar application](https://itunes.apple.com/us/app/wallpaperer-for-reddit/id1102248738?mt=12) lately which I found on one of the [Reddit threads](https://www.reddit.com/r/apple/comments/54aw5h/i_made_wallpaperer_a_mac_app_that_automatically/?st=j42szdlj&sh=b5691937) and there was a lot of positive feedback and appreciation from the community for it, so apparently, the larger audience is definitely intrigued by such an application.

Though I haven't used the app in question myself, so can't comment on its performance right now. But if its user experience and performance is great it's a +1 from my side.

@dkhamsing Your thoughts?

BTW, @srishanbhattarai it would be great if you can get some endorsements for this, it definitely increases the chances of this PR getting merged.

**Comment by dkhamsing** [comment]
I haven't tried this app but the idea of having a different beautiful wallpaper everyday sounds good :)

**Comment by dkhamsing** [comment]
Question: why is here a link to the project Helium??

**Comment by srishanbhattarai** [comment]
@dkhamsing The 3 AM must've gotten to me. Fixed it.

**Comment by herrbischoff** [comment]
See, the others found this application worthwhile while I just like to throw in my two cents. I'm completely honest about my opinion, as I firmly believe that's the only kind of feedback useful to anyone.

Regarding why I think a wallpaper changer does not qualify for being an "awesome" application is because U view the whole category of tools as absolutely superfluous. My measure is one of usefulness, be it to me or someone else, judged by whether it is truly adding value or is just a distraction. Wallpaper changers are a distraction as they don't help you in optimizing a task so much as present you with tons of new choices – by design. Given the addition of an application that does nothing more than change the wallpaper image, every smallish utility doing increasingly little tasks should get a shot at being included: image resize apps, image crop apps, currency converters, unit converters, font viewers, image converters, color pickers, … I would rather avoid an influx of what I view as crapware.

**Comment by srishanbhattarai** [comment]
A lot of people do like periodically changing beautiful wallpapers and find it quite freshening as opposed to distracting or superfluous.
We are of course entitled to our own opinions and I guess this one qualifies as worthwhile for others.
Cheers.

**Comment by ajnsit** [comment]
@herrbischoff Just to add my 2c -

There are people who change wallpapers regularly anyways, with or without a tool. For them irvue saves time, that would be otherwise spent looking for and downloading appropriate wallpapers.

Having used this for a couple days, this one seems to have just the right amount of features for me. These are the ones that I think make this app non-trivial -

  1. Allows browsing and combining channels. I combined "up above" and "nasa" channels to get beautiful space and google earth-esque wallpapers. The wallpapers look good even on a 5K screen.
  2. Dual monitor support. I can change wallpapers together or independently.
  3. Like/Blacklist/Download wallpapers.
  4. Can autochange your macos theme to light or dark depending on the background (interesting but it messes with some of my custom styling, so I disabled it)
  5. It's seems to be a well designed mac app, sits in the menu bar, and offers nice keyboard shortcuts.
  6. FOSS, AND in the Mac Store. It's a rare combination.

**Pull request merged**
