### PR TITLE
Add nehm

### PR DESCRIPTION
**Pull request by bogem**
0. [x] Project URL: https://github.com/bogem/nehm
1. [x] Why should this project be added: This app was created by myself and I think it can help for many SoundCloud users :)
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
Looks decent enough to me, @herrbischoff @dkhamsing thoughts?

**Comment by dkhamsing** [comment]
Uh looks good, except for the downloading music part...

**Comment by bogem** [comment]
@dkhamsing 

> except for the downloading music part...

What exactly?

**Comment by dkhamsing** [comment]
Is this illegal?

**Comment by bogem** [comment]
I think, yes

**Comment by herrbischoff** [comment]
@bogem: The absurdity of the situation is quite clear. However, the fact that anyone *feels* it should be their right to do anything does not invalidate the fact that this software is in clear violation of the SoundCloud TOS (or TOU).

I propose to not include it in this list, as the only use-case is the violation of said TOS. That being said, I agree that it's decent enough software (and especially appreciate it being written in Go). People determined to find it should be able to find it without this list.

**Comment by bogem** [comment]
I've understood. No problem

**Pull request closed without merging**
