### PR TITLE
Added WorkspacePro to productivity apps' list

### PR DESCRIPTION
**Pull request by OrkhanKerimli**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL:  https://workspaceproapp.com
2. [x] Why should this project be added: WorkspacePro is a native macOS app which allows users to launch a bunch of apps, files and also open URL addresses at the same time just with shortcuts or pressing the button in the menu bar. WorkspacePro featured in ProductHunt as [#1 Product of the Day](https://www.producthunt.com/posts/workspacepro)
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
Personally, not a fan. Up to you @herrbischoff @dkhamsing

**Comment by herrbischoff** [comment]
Seems rather useless to me and reinforces clutter.

**Comment by OrkhanKerimli** [comment]
@iCHAIT, @herrbischoff WorkspacePro can also close apps which launched by it. Our users use WorkspacePro to switch between workspaces fast and easily. 

For example: 
- A designer creates **GROUP 1**  (workspace) for work with Sketch app, Photoshop, color palette app, and URLs for inspirations. 
- And creates **GROUP 2** for with non-work apps, URLs, and files. 

Using WorkspacePro, a designer can **launch GROUP 1** with working apps, open URLs, and files together at the same time with just 1 shortcut then **close** apps of this workspace and switch to non-work **GROUP 2**.
The main feature of WorkspacePro is to save the time of users and increase their productivity.

**Comment by herrbischoff** [comment]
I do understand how it's supposed to work. However, in my view, the premise is flawed. If you require a tool like yours to keep all your stuff together, you have too much stuff. You're probably even Doing it Wrong™. At the very least you would profit from rethinking your workflow instead of spending time and using more software managing your clutter.

**Comment by dkhamsing** [comment]
It appears we do not support adding this to the list, thanks for the suggestion!

**Pull request closed without merging**
