### PR TITLE
Added Subtitlr to Video apps

### PR DESCRIPTION
**Pull request by spilja**

### CODE REVIEW

**Comment by iCHAIT** [comment]
@spilja  Hey, thanks for the suggestion, but I am not sure how to install this, so [I have opened an issue](https://github.com/spilja/Subtitlr/issues/1)

**Comment by iCHAIT** [comment]
Also I wanted to know how is it different from [flixtools](http://www.flixtools.com/)

**Comment by spilja** [comment]
It might not be, Subtitlr is probably simpler and it's open sourced, I haven't seen flixtools previously.

I'll build and upload an installation package later this afternoon and get back to you.

**Comment by iCHAIT** [comment]
@spilja  Looks Good to me, however I'd like to hold this for now as I believe it is a pretty application which not many features when compared to something like flixtools. (I hope you'd agree on this.) But having said that, I personally like Subtitlr but it is always nice to have feedback of other people as well.

@herrbischoff  Thoughts?

Needs +1

**Comment by spilja** [comment]
@iCHAIT whatever you decide is absolutely fine with me. As I said, I haven't seen flixtools before and I built this mainly for personal use and because Subtitles became a paid application :) After it was rejected from Mac App Store I decided to share it as open source.

**Comment by iCHAIT** [comment]
> whatever you decide is absolutely fine with me.

Thanks. Good to hear :D

>  I haven't seen flixtools before

Neither have I, for downloading subtitles I use [subliminal](https://github.com/Diaoul/subliminal) which is a pretty awesome application, it is open source too in case you want to have a look.

Another application that I use a lot is the VLC's built in extension for downloading subtitles [vlsub](https://github.com/exebetche/vlsub), again an open source application :)

**Comment by dkhamsing** [comment]
@spilja 
can you rebase/fix the conflicts?

**Comment by spilja** [comment]
@dkhamsing it should be ok now, thanks

**Comment by dkhamsing** [comment]
thx!

**Pull request merged**
