### PR TITLE
Added LastPass under Utilities.

### PR DESCRIPTION
**Pull request by sunpech**
Added LastPass password manager.

### CODE REVIEW

**Comment by dkhamsing** [comment]
Originally #181

**Comment by dkhamsing** [comment]
thx

**Comment by dkhamsing** [comment]
FYI 
LastPass "lite" is free to use on a single machine
Password sharing and other premium features require payment https://lastpass.com/enterprise/enterprise-pricing/

**Comment by sunpech** [comment]
LastPass Free plan is limited to one mobile device (phone, tablet, etc..), but should be free for any desktop machine running Windows, macOS, and Linux.

**Pull request merged**
