### PR TITLE
 Workspaces 

### PR DESCRIPTION
**Pull request by mkk**
0. [x] Project URL: http://www.apptorium.com/workspaces
1. [x] Why should this project be added:
It's a useful app.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

---

*edited*

### CODE REVIEW

**Comment by herrbischoff** [comment]
Please read the contribution guidelines and add the missing information.

**Comment by dkhamsing** [comment]
Can you fill out /  edit the description in the pull request

**Comment by mkk** [comment]
@dkhamsing which one exactly? It's my first time, sorry.

**Comment by herrbischoff** [comment]
@mkk: "It's a useful app." Are you serious? Is there truly absolutely nothing else you could think of, Captain Obvious? :P Being new doesn't absolve you of thinking and especially *reading*.

@dkhamsing, @iCHAIT: I get the feeling that we're becoming the go-to repo for highly inexperienced and rather willfully ignorant newcomers.

**Comment by mkk** [comment]
@herrbischoff Of course, I could write "It's an amazing app. You must add it, because I said so", but I wasn't convinced to such rhetoric. It's you who accept the applications here, so I don't think that my opinion matters so much (which is not bad in case of curated app directory!)

**Comment by dkhamsing** [comment]
fyi it says `beta` on the website

@mkk 
is there pricing info?

**Comment by mkk** [comment]
It's not beta anymore. It's 6 USD

**Comment by herrbischoff** [comment]
@dkhamsing, @iCHAIT: You decide. I'm not quite impartial as I wouldn't use any application in this particular area. I don't see the point. The approach invites clutter, leading to cluttered work, in my opinion.

**Comment by dkhamsing** [comment]
is this helping? https://news.ycombinator.com/item?id=14413463

**Comment by dkhamsing** [comment]
i am neutral
i do not use these apps either

**Comment by dkhamsing** [comment]
@mkk hey did you work on this app??

**Comment by mkk** [comment]
Yes, I did

**Comment by iCHAIT** [comment]
I am not too sure of this either, however, the HN thread shared by @dkhamsing reflects that this application is somewhat buggy (as per many people's experience on that thread) and people also regarded it as a very basic application for what it does, which may go against it for making it to this list at least.

**Comment by dkhamsing** [comment]
Closing
Thanks

**Comment by mkk** [comment]
@iCHAIT I'm sorry, but there were 2 people complain about bugs which they couldn't name when I asked to send details. We really wanted to help.
For some people the app is basic and for others it's just perfect. It depends on expectations only. In my opinion, and for my purposes (if I am the one who can have an opinion) it's perfect. 

Of course its your decision.

**Comment by iCHAIT** [comment]
> I'm sorry, but there were 2 people complain about bugs.

@mkk I did a `Cmd + F` on that thread and found at least 3-4 people who complained of the app being buggy directly or indirectly. However, I'll try to install this on my machine and give it a shot myself.

> For some people the app is basic and for other's it's just perfect. 

Agreed, but you should understand that this list has a pretty high standard for accepting new apps, and we'd me more inclined to accept a suggestion if it can be confirmed as a perfect app for its own kind by most of its user's. Having said that it would be great if you can rope in some endorsements from people who used this and found it to be perfect.

**Pull request closed without merging**
