### PR TITLE
Added Magnet to Window Management

### PR DESCRIPTION
**Pull request by airportextreme**
0. [x ] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x ] Project URL: http://magnet.crowdcafe.com
2. [x ] Why should this project be added: It is not only an excellent tiling window manager, it's also the top paid app on the macOS App Store, which means it took a tool used by UNIX geeks and into a mainstream product. Has excellent reviews and been prominently featured by Apple as a top utility and productivity tool. I have used it for quite some time myself, every day. It's well worth the $.99.
3. [x ] End all descriptions with a full stop/period
4. [x ] Entry is ordered alphabetically
5. [x ] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
Please explain why you didn't follow the contribution guidelines but checked them off?

https://github.com/iCHAIT/awesome-macOS/pull/404

**Comment by airportextreme** [comment]
I made a mistake, have you ever done that?

**Comment by herrbischoff** [comment]
Sure, I constantly make mistakes. But generally mine don't include ignoring three separate notices to read the freaking contribution guidelines, followed by not following them and finally simply checking them off. You did the same thing [here](https://github.com/herrbischoff/awesome-osx-command-line/pull/178), so I'm probably correct in assuming carelessness.

**Comment by airportextreme** [comment]
Only twice actually, there was no way searching would have detected the the third one, Upterm, because as you noted on #121 a few minutes ago the name had changed. 

As I've pointed out already, I am new here and to git, but I am very sorry I have wasted your precious, precious time.

**Comment by herrbischoff** [comment]
> As I've pointed out already, I am new here and to git

Where did you do that?

**Pull request closed without merging**
