### PR TITLE
Add ARHeadsetKit

### PR DESCRIPTION
**Pull request by philipturner**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: [https://github.com/philipturner/ARHeadsetKit](https://github.com/philipturner/ARHeadsetKit)
2. [x] Why should this project be added: Although this is geared toward iOS, it has several useful utility functions and types which can be bound to a Mac app under a separate framework. It includes a highly productive wrapper over MTLBuffer ([MTLLayeredBuffer](https://github.com/philipturner/ARHeadsetKit/blob/main/docs/articles/layered-buffer.md)), an API for experimenting with ray tracing, and convenient wrappers over the "simd" framework for optimizing math-intensive CPU operations and CPU-GPU communication. It also might be the only open-source framework with both inlinable Metal Shading Language functions and a live connection to GitHub like a Swift package (unlike [GPUImage3](https://github.com/BradLarson/GPUImage3), where you must copy the Xcode project from a ZIP file).
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by philipturner** [comment]
Who do I need to endorse this?

**Comment by philipturner** [comment]
I recently updated ARHeadsetKit to require Xcode 13.1 instead of 13.0 just so that the macOS build wouldn't fail. macOS support is something I take seriously.

**Comment by iCHAIT** [comment]
@philipturner You can get any current users of your app to endorse its inclusion to the list, that would make it easier for us to come to a decision. 

@herrbischoff @dkhamsing any thoughts on this?

**Comment by philipturner** [comment]
The problem is that I don’t have any users right now. I’m severely struggling to reach out to people, which is why I’m putting ARHeadsetKit on awesome-macOS.

It may be months ahead, but I plan to work on palle-k/DL4S in the future. Maybe I can find a way to incorporate ARHeadsetKit’s utilities into DL4S.

**Comment by herrbischoff** [comment]
Given that

> Xcode 13.1 or higher is required for working with ARHeadsetKit, and an iOS device running at least iOS 14.0.

it appears to be very niche (no problem in itself), experimental (difficult) and also focused exclusively on developers working **on iOS**. The only connection to macOS I can see is that Xcode on a Mac is needed to build iOS applications. I don't think it fits particularly well here.

@philipturner, maybe you're looking in the wrong direction. Two minutes on DuckDuckGo resulted in:

* https://github.com/vsouza/awesome-ios
* https://gitlab.com/yogeshc/awesome-ios
* https://github.com/matteocrippa/awesome-swift

You could also consider submitting it on Hacker News and see what happens. Just a couple of ideas off the top of my head to reach your intended audience.

**Comment by philipturner** [comment]
The connection to macOS isn’t just that Xcode is required to build it. If you read the repository’s README, it is has a standalone macOS framework that can be used independently of iOS.

Also, I have already reached out to every iOS awesome list you just mentioned, but very few are giving me responses.

**Comment by philipturner** [comment]
Not Yogeshi yet but I may look to that as well.

**Comment by philipturner** [comment]
Thanks for the Hacker News suggestion.

**Review by LucasLarson — APPROVED** [review]

**Comment by philipturner** [comment]
Thank you @LucasLarson

**Comment by herrbischoff** [comment]
Comparing https://github.com/dkhamsing/open-source-ios-apps/issues/989 (because I was mentioned), I'm going to lock this issue to prevent more stream-of-consciousness additions.

I still think the project is largely unrelated to this list. I'll leave the decision up to the other maintainers.

**Comment by herrbischoff** [comment]
As there has been no change in status of this, no other maintainer has chosen to respond and the author continues to exhibit questionable judgement regarding communication, I'm going to close this for good.

**Pull request closed without merging**
