### PR TITLE
Add Flotato

### PR DESCRIPTION
**Pull request by stackptr**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://flotato.com/
2. [x] Why should this project be added: Offers a native, non-Electron based solution to getting web apps out of the browser. Includes an "app store" for common such web apps. Seems to offer better stability and performance than Fluid, which is currently listed.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by stackptr** [comment]
This was [written up](https://www.theverge.com/2019/5/29/18644080/flotato-mac-web-apps-electron-fluid-webkit-slack-twitter) in The Verge and I've been using it daily since then. I've had no issues and it seems very performant. This is a competitor to Fluid, which is already listed, and I've used it in the past but was less satisfied with (experiencing lag in mouse events iirc). I have not used it recently to compare.

**Comment by herrbischoff** [comment]
Thanks for this suggestion and your other PRs, especially the proper descriptions and reasons given. This is how it should be! 🎉 

@iCHAIT: Just checked out Flotato, it's very nice. This one got my vote. It's also a great showcase of what you can do with macOS in ~22 MB instead of 220 MB with Electron. RAM usage is equal to a Safari tab process and not 2 GB+ as with Electron.

**Comment by iCHAIT** [comment]
This looks nice 👍 
@stackptr Thanks for your contributions. Can you please rebase your PR so we can merge. There were some dead links that I have fixed, so Travis should no longer fail.

**Comment by stackptr** [comment]
Rebased

**Pull request merged**
