### PR TITLE
Add Trailer to Developers section

### PR DESCRIPTION
**Pull request by stackptr**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://github.com/ptsochantaris/trailer
2. [x] Why should this project be added: Seems to be very flexible/configurable, written in Swift, and has a feature set that is not provided by other apps in this section.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
Why would you want to use a separate application just for managing issues? It appears to be rather unproductive since it's the only thing you can do with it. Additionally, I believe we're terrorized enough by notifications as is, so I really cannot see the point in getting GitHub notifications not only on my laptop but also on my phone and my watch (that I don't have). So, thumbs down from me because the whole premise of this app is flawed. Just because you **can** do something doesn't necessarily mean that you **should**.

**Comment by stackptr** [comment]
I needed something that could act as a persistent reminder for PRs on work projects that I sometimes defer and then forget about. For my purposes, this is actually the opposite of workflow disruption, as it (at least in theory, I've only used it for a few days) allows me to get to a satisfying stopping point before context switching to review mode. For what it's worth, I have most notifications turned off. I can't argue against your personal preference around using this app, but I do think that it fits the criteria of being on this list and that we are not required to personally use or endorse every app on the list.

**Comment by herrbischoff** [comment]
You’re entitled to your opinion and your recommendation is welcomed and will be considered. However, you should refrain from trying to explain to the actual maintainers what this list is for. To put it bluntly: you don’t get a say. If you disagree, happily start your own one.

**Comment by iCHAIT** [comment]
I think this is useful 👍

**Pull request merged**
