### PR TITLE
Pull Request Template

### PR DESCRIPTION
**Pull request by dkhamsing**
@iCHAIT 

Using GitHub's pull request template https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by dkhamsing** [comment]
Merged

**Comment by iCHAIT** [comment]
@dkhamsing I think the template should also have the following - 

- [ ] The app is open source and has OSS symbol which points to the source code
- [ ] The app is freeware and contains the freeware symbol.


What do you think?

**Comment by iCHAIT** [comment]
Also, FYI, while merging an app/software please make sure that it contains relevant badges. For instance in case the app is open source, it should end with the OSS symbol which points to the source code and if the app/software is **completely free** then it should have a freeware symbol.

**Comment by dkhamsing** [comment]
OK! I will review recent additions and make necessary changes

**Pull request merged**
