### PR TITLE
Add SpaceLauncher

### PR DESCRIPTION
**Pull request by oolugh**
0. [x] Project URL: https://spacelauncherapp.com/
1. [x] Why should this project be added:

Before macOS Sierra, I used to launch or switch to an app with [Brett](http://brettterpstra.com/contact/)'s ["hyper key" configurations](http://brettterpstra.com/2012/12/08/a-useful-caps-lock-key/). It remaps Caps Lock key (called "hyper key") to Command+Shift+Option+Control via [Karabiner](https://pqrs.org/osx/karabiner/), and use "hyper key" + another key to launch or switch to an app. It saved me a lot of time.

However, Karabiner is not compatible with macOS Sierra. After the upgrade, I really missed the configuration. Without "hyper key", I had to use Dock, Command+Tab, Launchpad or Mission Control to switch apps. I started to notice I was distracted with locating the target app I want to switch to.

SpaceLauncher lets users launch or switch to an app by holding down the spacebar while pressing a key. Spacebar is so easy to be pressed and combined with another key to switch apps. This makes my workflow much smooth and less distraction. I hope others can also benefit from SpaceLauncher.

2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
@oolugh: The project URL is missing in the description.

Apart from that: $14.99 is just unacceptable for this kind of application. If it were free or maybe $1-2, I'd endorse it. Personally, the space key setting would interfere with my Vim setup using space as the leader key. This is an edge case however. Still, this is in "useful helper" territory, doing one thing only (which is good). I would never pay for it, let alone $14.99.

**Comment by oolugh** [comment]
@herrbischoff Sorry, I can't believe I gave detailed reason but forgot the URL. I updated.

**Comment by oolugh** [comment]
@herrbischoff About the price, SpaceLauncher doesn't stop any functions after trial expiration. It seems only prompt an alert after hundreds of uses. So I guess the price is just a kind of donation.

**Comment by gviridis** [comment]
I love it! And the current price is $4.99!

**Comment by herrbischoff** [comment]
> I love it! And the current price is $4.99!

It wasn't when I checked the page. The current pricing is much closer to the mark in my opinion. Let's see what the others say.

In any way, good to see some endorsement. And thanks to @oolugh for writing up the reasoning behind his suggestion. I suppose that's because he's the author of the app. ;)

**Comment by herrbischoff** [comment]
Interesting: just noticed that the application is now completely free. That was fast. As soon as @dkhamsing or @iCHAIT review it and give the green light, we can probably merge.

**Pull request closed without merging**
