### PR TITLE
Signal chat app added

### PR DESCRIPTION
**Pull request by egberts**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL:
2. [x] Why should this project be added:  Multi-platform support, super-secured.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
1. This is not a macOS application but a link to the Signal GitHub organisation and repositories for multiple implementations.
2. The description is not descriptive but clumsy marketing copy.
3. @dkhamsing: Have we abandoned "No Electron apps" from the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)?

@egberts: Why did you set the checkmark on "I have read the Contribution Guidelines" when this is clearly an application not applicable to this list?

**Comment by dkhamsing** [comment]
@herrbischoff oops, thank you

**Comment by egberts** [comment]
Electron?  This is new to me. 

As a private and security advocate, this repo complied with all security and privacy and even allows end-users to build their own Signal chat iOS app from scratch.  Which is a step up better than Apple store.  

But, ok.

**Comment by herrbischoff** [comment]
@egberts: Well, this is a repository with a focus on macOS (not iOS), it's right in the title – and the first sentence in the [desktop version](https://github.com/signalapp/Signal-Desktop) Readme is:

> Signal Desktop is an Electron application that links with Signal on Android or iOS.

It's perfectly alright to be an end user, we all are to some degree. What you *should* do however is read and follow the contribution guidelines and do the basic research that takes less than a minute.

**Comment by egberts** [comment]
The download page responds to your OS platform;  Please check for the  'Signal for Mac' hyperlink for macOS.

**Pull request closed without merging**
