### PR TITLE
Add IINA, video player

### PR DESCRIPTION
**Pull request by LisaDziuba**
0. [x] Project URL: https://lhc70000.github.io/iina/
1. [x] Why should this project be added: It's a media player with a very nice UX.  It can do frame by frame smooth video scrubbing and it loads very quickly. It’s free, which definitely a bonus. I personally don’t know the guy, who developer IINA, but I’m sure he spent a decent amount of time on it.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by dkhamsing** [comment]
Looks pretty good, only flag is that it is alpha

**Comment by LisaDziuba** [comment]
hmm... Is there any badge for alpha or how to flag it? 
Didn't find it in Contribution Guidelines.

**Comment by dkhamsing** [comment]
Hmm @herrbischoff @iCHAIT .. how do you feel about alpha software?

**Comment by LisaDziuba** [comment]
@dkhamsing, it's always a risk, that product might stay in alpha and there will be bugs ಠ_ಠ
For now IINA works fine for me, will see how it goes. Maybe it's reasonable to wait until beta will be released.

**Comment by herrbischoff** [comment]
> Maybe it's reasonable to wait until beta will be released.

Or maybe wait until a **stable** beta is released. Alpha development software may be awesome but it's stability is often not. So in doubt: not awesome (yet).

**Comment by dkhamsing** [comment]
Let's close it for now
Thanks @LisaDziuba, we should definitely revisit this

**Pull request closed without merging**
