### PR TITLE
Add Versions SVN app

### PR DESCRIPTION
**Pull request by forgottenleaf**
SVN GUI.

### CODE REVIEW

**Comment by forgottenleaf** [comment]
I fixed the failed test in this (due to NepTunes) in PR #258.

**Comment by dkhamsing** [comment]
can anyone else vouch for this app

**Comment by herrbischoff** [comment]
👍 It's the best one for macOS.

**Comment by herrbischoff** [comment]
@forgottenleaf: Please fix the conflicts so this can be merged. Thanks.

**Pull request merged**
