### PR TITLE
Giphy capture

### PR DESCRIPTION
**Pull request by sunpech**
Added Giphy Capture link. 

Also seemed to removed space and end of line of another link.

### CODE REVIEW

**Comment by dkhamsing** [comment]
looks pretty good
can you rebase/fix the conflicts?

**Comment by sunpech** [comment]
@dkhamsing Should be good to go now, merged from latest master.

**Comment by dkhamsing** [comment]
the diff doesn't look so good, maybe easier to close and reopen
sorry!!

**Comment by dkhamsing** [comment]
@sunpech let me know if you'd like me to add it

**Pull request closed without merging**
