### PR TITLE
Add Magnet

### PR DESCRIPTION
**Pull request by Dedados**
0. [x] Project URL: https://itunes.apple.com/us/app/magnet/id441258766?mt=12
1. [x] Why should this project be added: It is a very useful Window Management app with a great feature allowing windows to be dragged to the edge of the screen to expand.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by dkhamsing** [comment]
How much is it

**Comment by Dedados** [comment]
0.99 Euro.

**Comment by herrbischoff** [comment]
You can get all of this in the free and open source Spectacle. There's also BetterSnapTool, Amethyst, kwm, … What sets Magnet apart from those, not counting being popular in the Mac App Store?

**Comment by herrbischoff** [comment]
BTW: "It is a great addition to this list, making it more useful!" is not a valid reason. This is highly subjective and offers no concrete example for **what it is** the app does great, especially what it does **better** than other entries in its field. Please elaborate.

**Comment by Dedados** [comment]
I didn't phrase my reason well. The app is nothing special, it virtually does the same as other apps but I saw it wasn't in the list and thought why not include it, it will make the list more useful. That is why I said: 'it is a great addition to the list, making (the list) more useful'.

**Comment by dkhamsing** [comment]
Closing
Thanks for the suggestion

**Comment by Dedados** [comment]
Why not include it?

**Comment by herrbischoff** [comment]
Because this is an **Awesome List**. We strive to include only the best applications of any kind. In your own words:

> The app is nothing special, it virtually does the same as other apps but I saw it wasn't in the list and thought why not include it

This is decidedly not the definition of being "awesome".

**Comment by Dedados** [comment]
Ok, thanks for clarifying your reasoning:)

**Comment by herrbischoff** [comment]
Thanks for being understanding. :)

**Comment by lordgiotto** [comment]
My 2 cents: I've used both Spectacle, Better Snap (and Touch) Tools and Magnet.

With its small .99 cents cost, Magnet is really worth it! 

I found it to be less buggy than better snap tools (which costs 3 times more); compared to Spectacle it gives the same powerful keyboard shortcuts and the drag and drop edge resize.

So, in my opinion, it's more *awesome* than the mentioned alternatives 😉

**Comment by Dedados** [comment]
Since I have never used others, I cannot comment on them but I think magnet is worth it as it works flawlessly. It is also the only tool I know of (other than moon) which gives you the ability to resize by dragging to the edge of the screen.

**Comment by Dedados** [comment]
In fact, I just checked and it is also 10x cheaper than moom despite doing the same job. Moom has a few more tools but that makes it unnecessarily complicated for the things I and expect others would do.

**Comment by dkhamsing** [comment]
Thx for the endorsement
Let's have @iCHAIT weigh in

**Comment by iCHAIT** [comment]
I use spectacle and it works pretty good for me so haven't felt the need to look for its alternatives, haven't used Magnet so can't comment much on that, however @lordgiotto endorsement of the app seems pretty legit to me. Maybe we can reopen this and place a **Need Endorsement** label on it and if we get another +1 we add it to the list, does this sound good?

**Comment by Dedados** [comment]
Good idea.

**Comment by dkhamsing** [comment]
let's close this, lack of endorsements 😅

**Comment by Dedados** [comment]
Seems like there wasn't 'attraction'.

**Pull request closed without merging**
