### PR TITLE
Added Disk Inventory X

### PR DESCRIPTION
**Pull request by seanoh1989**

### CODE REVIEW

**Comment by dkhamsing** [comment]
can you rebase/fix the conflicts?

**Comment by dkhamsing** [comment]
@seanoh1989 hey there
can you rebase/fix the conflicts?

**Comment by seanoh1989** [comment]
what conflict did this cause? I'll take a look at it when I get home. I'm at work.

**Comment by dkhamsing** [comment]
Your fork and our repo have diverged

**Comment by herrbischoff** [comment]
What I just remembered: doesn't this application look suspiciously similar to issue #94, which was closed back then?

**Comment by dkhamsing** [comment]
@herrbischoff you know I think Sierra will ship with something to detect large files and improve managing space

Closing

**Pull request closed without merging**
