### PR TITLE
Add Timing for Mac (automatic time tracker)

### PR DESCRIPTION
**Pull request by MrMage**
Project page: https://timingapp.com

This commit adds another time tracking app to the list. For testimonials of its awesomeness, see [our Product Hunt page](https://www.producthunt.com/posts/timing-2-3) and [the old version's Mac App Store page](https://itunes.apple.com/us/app/id431511738?mt=12&ign-mpt=uo%3D4). Also happy to send you a free copy so you can see for yourself :-)

Was also suggested in #431 already.

### CODE REVIEW

**Comment by dkhamsing** [comment]
FYI cost is $29

**Comment by herrbischoff** [comment]
I'm a long-time user of version 1 and fully endorse it. I haven't tried version 2 yet, so a way to use the updated version would be most appreciated. :)

**Comment by dkhamsing** [comment]
thx!

**Comment by dkhamsing** [comment]
@MrMage can you send @herrbischoff a copy :)

**Comment by MrMage** [comment]
Sent a license to @herrbischoff :-)

**Pull request merged**
