### PR TITLE
Add Hummingbird

### PR DESCRIPTION
**Pull request by finestructure**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://hummingbirdapp.site
2. [x] Why should this project be added: It's a new window management app that goes well with others in this category.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by finestructure** [comment]
This seems to have failed on a check unrelated to my addition:

```
Issues :-(
589> Links 
590  1. [L171] 500 https://macsvg.org/  
591
592
```

Is there a way for me to re-trigger CI? (Short of pushing some commit.)

**Comment by dkhamsing** [comment]
Don’t worry about the check, we can take care of that separately.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by finestructure** [comment]
Ah cool - I thought that's what's blocking the merge 😅

Is there anything else I should amend?

**Comment by dkhamsing** [comment]
No, now we just need someone on the team to review the app 🙏

**Comment by iCHAIT** [comment]
Nice 👍

**Pull request merged**
