### PR TITLE
Giphy capture

### PR DESCRIPTION
**Pull request by sunpech**
Added Giphy Capture (again).

### CODE REVIEW

**Comment by sunpech** [comment]
See https://github.com/iCHAIT/awesome-macOS/pull/295

**Comment by dkhamsing** [comment]
@sunpech sorry the diff is totally wrong if you look here https://github.com/iCHAIT/awesome-macOS/pull/330/files
can u do anything about this

**Comment by dkhamsing** [comment]
It should only show Giphy as a new app
Also the entry needs the freeware icon

**Comment by dkhamsing** [comment]
thx!

**Pull request merged**
