### PR TITLE
Added AppBox

### PR DESCRIPTION
**Pull request by vineetchoudhary**
0. [X] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [X] Project URL: http://tryappbox.com or http://appstorebeta.com
2. [X] Why should this project be added: This is the only tool/service for the iOS developer to share the iOS development application without any charge with unlimited storage and without expiration. 
3. [X] End all descriptions with a full stop/period
4. [X] Entry is ordered alphabetically
5. [X] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
@herrbischoff @dkhamsing thoughts?

**Comment by herrbischoff** [comment]
I'd argue that the UI is rather... unfortunate. Also, I couldn't figure out why it's tied to Dropbox. Any online storage should do. So 👎 from me.

**Comment by vineetchoudhary** [comment]
Hi @herrbischoff, 

I think you don't know much about the iOS wireless installation process. For iOS wireless installation all associated files (manifest and IPA) must be directly downloadable without any redirection (for large size file too). So, Dropbox is the only service which provides the direct download link to a file. No other major online storage service provides this. Like, google drive does the virus scan for large size file.

For UI part, It does the job.  For most of the developers, UI doesn't matter. Also, I think, the installation page UI good enough.

**Comment by herrbischoff** [comment]
I meant FTP/SFTP/WebDAV/… Private storage under your control. The argument that UI/UX doesn’t matter runs contrary to the Apple HIG and disqualifies this app further for me.

As my position is clear, I’ll let the other contributors decide.

**Comment by vineetchoudhary** [comment]
AppBox has a private server mode which only available on your local network. Also, in future, I'm going to support FTP. 

screen shot 4

**Comment by iCHAIT** [comment]
> . For most of the developers, UI doesn't matter. 

Really?

**Pull request closed without merging**
