### PR TITLE
Add FinderGo

### PR DESCRIPTION
**Pull request by onmyway133**
0. [x] Project URL: https://github.com/onmyway133/FinderGo
1. [x] Why should this project be added: It helps open terminal from Finder, which we  need 100 times a day
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
This application is a pointless and convoluted way to do simple one line commands inside Terminal to achieve the same. To do the same from terminal is even easier: `open .`

**Comment by onmyway133** [comment]
@herrbischoff Hi, you may read it wrong. `open .` from Terminal will open Finder. While this allows us to open Terminal from Finder

**Comment by herrbischoff** [comment]
Nope. [This](https://github.com/herrbischoff/awesome-osx-command-line/blob/master/README.md#change-working-directory-to-finder-path) is all you application does.

**Comment by onmyway133** [comment]
@herrbischoff I think you have your point. Thanks for your time

**Comment by herrbischoff** [comment]
Sure. It's a nice learning project to get acquainted with Swift but unfortunately does not qualify for this list.

**Comment by iCHAIT** [comment]
@herrbischoff I get where you are coming from. However, the fact that this is fairly popular within the community, makes me think twice.

Also since this is an awesome list, I think we should add software that is indeed awesome and mac oriented (which this one is). I understand that what this app does can be done via a shell command, but I have seen people using such apps. I think it would definitely be useful for some of the people out there.

@dkhamsing what do you think?

**Comment by herrbischoff** [comment]
Comment on wrong PR? ;)

Yeah, that's exactly why I'm now standing neutral on this. I can see people using something like this even if I wouldn't.

**Comment by iCHAIT** [comment]
> Comment on wrong PR?

Haha, sorry my bad.

Yeah, so I'll reopen this one as well? And put an endorsement tag on both (this one and #521)

**Pull request closed without merging**
