### PR TITLE
Added Outlinely to Productivity section

### PR DESCRIPTION
**Pull request by datluong**
App Description: A powerful text editor for writing and organizing notes, plans, todos.

### CODE REVIEW

**Comment by dkhamsing** [comment]
$20, there is a free lite version

**Comment by iCHAIT** [comment]
Looks good, but seems expensive for what it does.
@herrbischoff thoughts on this?.

**Comment by herrbischoff** [comment]
I'd rather include the best-in-class Outliner: https://www.omnigroup.com/omnioutliner/

**Comment by dkhamsing** [comment]
Will add that instead, thx

**Pull request closed without merging**
