### PR TITLE
Adding Disk Inventory X, another Disk Analyzer Tool

### PR DESCRIPTION
**Pull request by napcae**
0. [x] Project URL: http://www.derlien.com/
1. [x] Why should this project be added: (free) Alternative to Daisy Disk
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
@herrbischoff @dkhamsing what do you think guys?

**Comment by vassyz** [comment]
I like it mostly because of the "End all descriptions with a full stop/period" feature. Jokes aside, this doesn't look awesome to me. Hasn't been updated in 11 years!

**Comment by napcae** [comment]
@vassyz It follows KISS, still works and is open source. The "feature" is just the template which comes with the PR.

**Comment by dkhamsing** [comment]
Dupe of #179 which was not accepted

**Pull request closed without merging**
