### PR TITLE
Add HyperTerm to Terminals

### PR DESCRIPTION
**Pull request by soul-wish**
0. [x] Project URL: https://github.com/zeit/hyperterm
1. [x] Why should this project be added: 

> HyperTerm is an awesome terminal built on web technologies. 

2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
LGTM

**Comment by herrbischoff** [comment]
This is:

a) an Electron app
b) far less capable than Terminal.app itself
c) alpha quality software

I tried HyperTerm along with the other Electron terminal called [Black Screen](https://github.com/shockone/black-screen). Apart from their flashy features like completion, both terminal emulators are significantly inferior to Terminal.app. Unless at the very least `b)` and `c)` change, I vote against including it. You know my opinion of Electron apps. Plus, I don't get why you would want to implement a terminal emulator in JavaScript to run it **locally**... Darn hippies! 💇

😄

**Comment by soul-wish** [comment]
@herrbischoff so Nylas N1, Atom and others in this awesome list are ok (they are also build with Electron)? 😉

**Comment by dkhamsing** [comment]
Can you answer this question

Why would you use this over Terminal or iTerm

Seems like this is very slow

**Comment by herrbischoff** [comment]
@soul-wish: Apart from Atom I don't feel any other app belongs on this list but they were added before I collaborated. My opinion does not reflect the teams'. Besides, please read my comment again carefully.

@dkhamsing: Good question.

**Comment by soul-wish** [comment]
@dkhamsing I'm web developer, so these apps are just "closer" to me. I can create my own plugins, themes and extensions just with my knowledge in CSS and JS. I'm not sure if they are really so slow (I didn't notice it in my HyperTerm daily usage). Surely, Electron has it's own problems with perf but sometimes you can live with them (my main editor is Atom just because it is much more extendable than Sublime Text (I was a Sublime Text user for 3 years before and I still use it in case I need to work with a really big files)). 

@herrbischoff sure, everyone has their own opinion and this is the right thing. And I'm not forcing you to merge this PR (thats why it called Open Source 😉). I just want to make it clear that many really awesome products were build on the top of Electron (that was my comment about) and decided to share one more with people. Anyway, thanks for such a great list and all your work!

**Comment by iCHAIT** [comment]
@herrbischoff @dkhamsing So should we close this?

**Comment by herrbischoff** [comment]
I'm going to go ahead and close it. If you feel it should not be, please reopen. Perhaps when HyperTerm has matured enough to be as useful as Atom is, we can add it. However, I still feel strongly about the ill-considered notion that everything that *can* be written in JS *should* be written in JS. I'm off now learning some more ObjC and Swift to put my money where my mouth is. ;)

**Comment by iCHAIT** [comment]
Hey @herrbischoff  on a different note can you take out some time and open a PR removing all electron wrapped applications from the list, in my opinion we should treat an application on its merit, having said that your argument on electron wrapped apps does not sounds entirely wrong to me. So maybe we can discuss that issue on a separate PR where we would be able to single out each application and discuss it?

If not possible for you, I can go ahead and open a PR for this myself, just let me know :)

**Comment by herrbischoff** [comment]
@iCHAIT, I'm getting right on it a little later in the day.

**Comment by iCHAIT** [comment]
Thanks :+1:

**Pull request closed without merging**
