### PR TITLE
Add FlagTimes to Productivity

### PR DESCRIPTION
**Pull request by reimertz**
Hi there, I hope you all find my tool worthy of this list.

 - [x] I have read the Contribution Guidelines
 - [x] Project URL: https://www.flagtimes.com
 - [x] Why should this project be added: Useful for anyone interacting with people in multiple timezones.
 - [x] End all descriptions with a full stop/period
 - [x] Entry is ordered alphabetically
 - [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
This appears to be a rather useless utility because all it does is show different time zones. The premise of "working with people in different time zones" arguably applies mainly to scheduling. The macOS Calendar.app already provides features to compensate for time zone differences. In my view, this would be alright for a free or open source application but being commercial it disqualifies itself immediately. Apart from that, it simply does not qualify as being awesome. It's less than mediocre at best, squarely among the tens of thousands of apps coding beginners flood the Mac App Store with. I wish people would just stop submitting what amounts to nothing more than a learning project from a code bootcamp. Seriously, stop it. No one wants your alarm clock, world timer, color picker, icon converter or wallpaper catalog.

For anyone interested in time zone display beyond the calendar, there are far better alternatives like [iStat Menus](https://bjango.com/mac/istatmenus/) or if you're really serious about it: [WorldClock Pro](http://worldclock.pro).

**Comment by reimertz** [comment]
Wow, I assumed there could be constructive feedback but instead got a rant.

This started as a tool for just myself, a hardcoded utility, showing the timezones I wanted, but friends and people at the several co-working places I went to started asking for it so I spent some time implementing it and eventually released it.

I didn't think much about it, got some people buying it every now and then, but then someone posted it on [ProductHunt and it turned out second of the day](https://www.producthunt.com/flagtimes-2). I was humbled and felt that maybe I should spend some time spreading the word about it so more use it.

I gotta say, this is the worst experience I've ever had in a community that is all about being inspiring, supportive and constructive.

**Comment by herrbischoff** [comment]
This is an Awesome list. Your application is not awesome by any standard. What did you expect? We’re not a review service or support community, we’re curating outstanding applications. One could argue that submitting your clearly not awesome app is a bad experience for us as well.

**Comment by reimertz** [comment]
> We’re not a review service...

It definitely seems like it. You had two options, you could just say "Sorry, this doesn't fit for this list but good luck in the future. 🙌" 

You instead went down the other route, reviewing it til core, making sure I know that the app sucks, looks like a coding beginners project and is less than mediocre at best just like the tens of thousands of apps out there. 

Luckily, I won't get effected by this, because I've done this for quite some time now and will continue to do just that, because it's so much fun.

What is really sad here is that this could've been someone else who maybe just started to learn coding, created their first app and really felt it to be awesome and worthy of this list. You would've killed their motivation, joy to the project which they are creating but also affecting anyone reading this conversation.

If you cannot see that, that I strongly worry for future submitters who might get a similar _review_.

**Comment by herrbischoff** [comment]
You’re welcome.

**Comment by mischievous** [comment]
I have to agree with reimertz.   You could of just said not for this list.  

If your requirement is "Awesome - https://www.merriam-webster.com/dictionary/awesome".  90% of the software on the list is not awe inspiring.  Just pursuing the list right now most if it is like the app mentioned here which is a little utility for time zones.  

Maybe for what ever reason someone does not want to use  iStat Menus or WorldClock Pro.

Want to say more, but I was raised not to.

**Comment by herrbischoff** [comment]
I do not feel like discussing the fundamental why's of why-not's of including applications. I am one of several maintainers, so I suggest to take your qualms up with them. Maybe they will overrule my views, which is fine by me. If my opinion is considered being too strong, next time I may simply decline, even if the follow-up will inevitably be the question "why?" — and any explanation whatsoever will lead back to discussing the personal definition of "awesome". This happened several times already.

**Pull request closed without merging**
