### PR TITLE
adding temps to others list

### PR DESCRIPTION
**Pull request by jackd248**
0. [x] Project URL: https://jackd248.github.io/temps/
1. [x] Why should this project be added: A simple but smart weather app. Easy to use, always needed on every desktop.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
Hey, thanks for the PR, but I am facing [an issue](https://github.com/jackd248/temps/issues/3) while using the app.

**Comment by iCHAIT** [comment]
Okay. To be very honest I don't think I would take the pain of signing up to a third party service, obtain an API key which in turn would allow me to your application.

For checking the weather on my mac, I currently use [Degrees](https://itunes.apple.com/in/app/degrees-weather/id430173763?mt=12) which looks pretty good to me and does not require the user to sign up for getting any sort of an API key, that app is free as well so I was wondering if you can/would like to go for an alternative free weather information service which does not require the end user to get an API key himself. I mean I am not interested in doing all that myself and taking that pain, and for people out there who are not technical, how do you expect them to use the application? I am not sure how inclined they would be to follow a procedure that may prove to be intricate to them.

**Comment by jackd248** [comment]
Of course, you don’t need to do this, if you don’t want to. 
This is a personal project with no commercial thoughts. But if you want unlimited weather data from a official api, you need to pay for it. If I will use a personal api key from a open source, the data is limited by a specific number of api calls per minute. So this is a good compromise for me and many others of the open source community. 
I have learned much while programming this app and having much more fun to be creative. I thought it could be interesting for others too, but for some it is obviously too much pain at all. And these instructions are marked very well on the web page and are really simple at least. 
But thanks for giving it a try, hope you enjoy using one of the many others weather apps. ;)


-- 
Konrad Michalik
konradmichalik.eu 

Am 25. September 2016 um 19:21:23, Chaitanya Gupta (notifications@github.com) schrieb:

Okay. To be very honest I don't think I would take the pain of signing up to a third party service, obtain an API key which in turn would allow me to your application.

For checking the weather on my mac, I currently use Degrees which looks pretty good to me and does not require the user to sign up for getting any sort of an API key, that app is free as well so I was wondering if you can/would like to go for an alternative free weather information service which does not require the end user to get an API key himself. I mean I am not interested in doing all that myself and taking that pain, and for people out there who are not technical, how do you expect them to use the application? I am not sure how inclined they would be to follow a procedure that may prove to be intricate to them.

**Comment by iCHAIT** [comment]
Yeah, it is definitely an interesting piece of work and it makes for an awesome side project to have, but as far as accepting an application into an awesome list is concerned the rules are a bit stringent as it is bound to have only applications that are really awesome and that anyone and everyone can use without a hitch (I know that it sounds a bit harsh, but that is how it works). So at this stage I don't find that this fits the list.

Thanks for the PR anyway, and keep up the good work :)

**Pull request closed without merging**
