### PR TITLE
Add Inkdrop to Developers section

### PR DESCRIPTION
**Pull request by noradaiko**
0. [x] Project URL: https://www.inkdrop.info/
1. [x] Why should this project be added: A good alternative to Evernote for taking notes about programming
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

Thank you for making great curated list!!

### CODE REVIEW

**Comment by iCHAIT** [comment]
Looks good

**Comment by herrbischoff** [comment]
I'm voting 👎:

- it does not allow for a trial without an account
- it probably is an Electron app
- it is basically just another Markdown editor
- a coding tool that needs a continued paid subscription to be usable is bad form
- especially for something like notes
- there already is a "pay once and keep it forever" alternative on the list: Quiver

**Comment by iCHAIT** [comment]
> It does not allow for a trial without an account

This is particularly odd, I thought all apps allowed a trial version without having to sign up or sign in :/

> It is basically just another Markdown editor

@herrbischoff Do you think we should have a separate sections for Markdown editors as there are a few of them in the list already?

> a coding tool that needs a continued paid subscription to be usable is bad form

This is a negative point indeed.

**Comment by herrbischoff** [comment]
I believe it does not allow for a trial without account because it is a web app. It probably requires a connection to even work.

As for the Markdown editors, I feel we should rather concentrate on the best of them and leave out the rest. I propose to group all of them along with the code editors under something like "Text Editors".

**Pull request closed without merging**
