### PR TITLE
Add Kite Compositor

### PR DESCRIPTION
**Pull request by LisaDziuba**
0. [x] Project URL: https://kiteapp.co/
1. [x] Why should this project be added:  powerful tool for both prototyping & work with animations.
It has Framer-esque scripting + Timeline based animation. The price is $99 and they have free trial. 
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
This looks promising. Do you work regularly with this application so you can vouch for its quality?

**Comment by LisaDziuba** [comment]
@herrbischoff I played with it via the weekends. I worked fine for me and was easy-to-use. But I found some people posting, that it was crazing (over the Reddit).

**Comment by LisaDziuba** [comment]
I will ask some more friends, who were interesting to try Kite Compositor as well.
As a new tool (I know has went out publicly just recently) it might be some stability issue. However, I personally didn't notice that

**Comment by herrbischoff** [comment]
That's great. If they can endorse the tool here, it has a far better chance of being added.

**Comment by dkhamsing** [comment]
let's close this, lack of endorsements
thx

**Pull request closed without merging**
