### PR TITLE
Add links to 2 CLI tools

### PR DESCRIPTION
**Pull request by dufferzafar**

### CODE REVIEW

**Comment by herrbischoff** [comment]
I'm absolutely no fan of simple wrappers that amount to little more than a collection of functions. 👎

**Comment by dkhamsing** [comment]
If you live in the terminal, these cli tools might be pretty useful

**Comment by iCHAIT** [comment]
+1 from me too

**Comment by herrbischoff** [comment]
@dkhamsing: I do live in the terminal but I dislike these helper function collections. Judging from the reactions here and all over GitHub, I seem to be in the minority though.

**Comment by dkhamsing** [comment]
@herrbischoff you have very strong opinions, I like that

**Comment by herrbischoff** [comment]
> you have very strong opinions, I like that

I have a rather Jobsian approach to the things I do (or not do):

> “People think focus means saying yes to the thing you've got to focus on. But that's not what it means at all. It means saying no to the hundred other good ideas that there are. You have to pick carefully. I'm actually as proud of the things we haven't done as the things I have done. Innovation is saying no to 1,000 things.”

**Pull request merged**
