### PR TITLE
Add Batch Image Resizer

### PR DESCRIPTION
**Pull request by brunowego**

### CODE REVIEW

**Comment by brunowego** [comment]
@iCHAIT you can merge it too?

**Comment by dkhamsing** [comment]
looks ok
can you rebase/fix the conflicts?

**Comment by herrbischoff** [comment]
I'm not sure about this one. A simple Automator workflow essentially does the same that this application does:

screen shot 2016-07-16 at 19 30 26

However, this may be to "geeky" for a regular user. I leave the decision to @dkhamsing.

**Comment by dkhamsing** [comment]
ok thx

**Comment by dkhamsing** [comment]
@brunowego 
can you rebase/fix the conflicts?

**Pull request closed without merging**
