### PR TITLE
Add Qbserve

### PR DESCRIPTION
**Pull request by ivmirx**
- [x] Project URL: https://qotoqot.com/qbserve/
- [x] Why should this project be added: a time tracker designed for Mac, it stores all your data locally and doesn't require subscription (I'm the developer of the app)
- [x] End all descriptions with a full stop/period
- [x] Entry is ordered alphabetically
- [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by vassyz** [comment]
I've been using this app since day one; I think it was a HackerNews post. I can confirm it deserves to be on this list. One big downside to it would be the price, but quality-wise, I have no complaints.

**Comment by herrbischoff** [comment]
<https://timingapp.com> comes to mind as an alternative, which is what I use. It's also $10 less.

**Comment by dkhamsing** [comment]
Not too familiar with this space, the app looks good

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
