### PR TITLE
Add email app

### PR DESCRIPTION
**Pull request by scipe**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [X] Project URL: https://sparkmailapp.com/
2. [X] Why should this project be added: I have been used Airmail since it was created and in 2019 I decided to switch all my devices on Spark Mail because Airmail was out of updates and totally broken on iOS. Spark mail team did all the same features and it was really great.
3. [X] End all descriptions with a full stop/period
4. [X] Entry is ordered alphabetically
5. [X] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by stackptr** [comment]
Previously suggested in #388

**Comment by scipe** [comment]
About the prev PR - I saw it, but it was 2016.. it was the real beta or something.

**Comment by herrbischoff** [comment]
I'm strictly against adding an application that misleads users. They save your account access credentials(!) and all your email(!) on their infrastructure to "provide enhanced services" (like send-it-later) without being clear about this at setup time. I've even had words with their DPO about it and found their attitude towards privacy to be cavalier at best. Therefore, a strong "no" from me.

**Comment by scipe** [comment]
This is make sense.
From my side I didn't catch privacy issue or bugs and me experience was great to maintain all my boxes.
Even in this case I would like to suggest reject the PR or add additional notice into row with this app with small alert or smth like that.

**Pull request closed without merging**
