### PR TITLE
Make contributing guidelines more visible

### PR DESCRIPTION
**Pull request by thomaskuntzz**
Make contributing guidelines more visible by moving them to the root.

Might be useful, I din't see them before submitting my first PR... 😉

### CODE REVIEW

**Comment by herrbischoff** [comment]
Well, it's just that GitHub automatically adds this as a notice above each pull request. It's probably not too visible but it's there.

**Comment by thomaskuntzz** [comment]
Yep, it's up to you to merge or not 😉

**Comment by thomaskuntzz** [comment]
I think [this](https://github.com/iCHAIT/awesome-macOS/commit/ea4eb62f5afb69ba2065ceb51cd18f1ced713cab#diff-195a635ad245ded9076330e31134bd80R5) was the most important thing to do. But it won't hurt to put CONTRIBUTING.md at the root, that's why I did it 🙂

**Comment by airportextreme** [comment]
But then @herrbischoff won't be able to be rude to people.

**Comment by thomaskuntzz** [comment]
@airportextreme is it supposed to be a joke?

**Comment by herrbischoff** [comment]
Sadly, no. He has already been reported to GitHub for his unacceptable conduct multiple times now. Even vandalized his own pull requests. He appears to have some serious behavioral issues.

There’s a great comparison that comes to mind: “if you think that everyone around you is an a-hole, then maybe, just maybe, the true a-hole is you.”

@iCHAIT: Please block this troll so we can be done with this.

**Comment by ajnsit** [comment]
@herrbischoff Just my two cents as a non-contributor (I just watch this repo to get to know about interesting software). I agree that @airportextreme was totally out of line, but can't help but point out that he was trying to *contribute* to an open source project, not trying to get free help. You are absolutely free to reject their contributions if you don't deem them acceptable, but that quote doesn't apply.

**Comment by herrbischoff** [comment]
If you take it as inspiration instead of at face value, it does. The statement about being alert, thoughtful, observant and willing to be an active partner translates rather well. Don’t be a loser, be a winner.

And now, please, let’s not discuss this further and put it behind us. It’s not worth to spend any more time on this little distraction.

**Comment by iCHAIT** [comment]
@herrbischoff Done.

**Comment by herrbischoff** [comment]
@iCHAIT Thanks. I'm locking this discussion just in case.

**Pull request closed without merging**
