### PR TITLE
Added a new category called 'Remote Tools' (as lot of us are wfh nowadays)

### PR DESCRIPTION
**Pull request by rampatra**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: I have added the URLs for the respective apps.
2. [x] Why should this project be added: These are great apps used by many with awesome developers behind them.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
I don't see the need for an arbitrary section like this. The examples moved there concern presentations and video conferencing. Both areas existed well before widespread WFH and independent of this particular use case.

**Comment by dkhamsing** [comment]
@rampatra maybe we can consider adding Lungo and Meeter ? Could you create one pull request per suggestion

Thx!

**Comment by iCHAIT** [comment]
Please open a separate PR for each recommendation. Also, I think it would be better to add these tools in either Productivity or Utility.

**Comment by herrbischoff** [comment]
Don't know about you but I really have to say I'm growing tired of all the malformed drive-by pull requests.

**Pull request closed without merging**
