### PR TITLE
added polyphone soundfont editor

### PR DESCRIPTION
**Pull request by clsource**
0. [x] Project URL: http://polyphone-soundfonts.com/en/
1.  [x] Why should this project be added: Helps creating sound fonts for music creation.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
screen shot 2016-10-30 at 15 32 23

@clsource: Seriously? This is your idea of "awesome"?

**Comment by clsource** [comment]
I think awesome is more than how it looks.
How helpful is a consideration too when using the awesome adjective.

This software helped me making awesome and beautiful music in many occasions.
Is a shame this awesome list is curated by such simplistic criteria.

**Comment by dufferzafar** [comment]
@clsource I agree that looks aren't everything, but the thing is - I don't know much about the problem domain (music, tunes etc.) either, so being able to decide how useful the software really is tough. I'm not sure if we have a similar application on the list to just compare features.

**Comment by herrbischoff** [comment]
> I think awesome is more than how it looks.

This is a given. However, if we let software like this on the list, we would also have to add a whole bunch of other, quite hideous applications. Applications which we recently summarily removed: #372 For a couple of those it could be argued to that they add really good value. Still, while they may be regarded as "awesome" in one way or the other, what they are *certainly not* is awesome macOS applications.

I don't see any reason to backtrack on that decision.

**Comment by clsource** [comment]
I'm ok with your decision.
If you want more applications for music and audio making in the list.
here are some. 

http://www.reaper.fm/
http://littlegptracker.com/
http://www.deflemask.com/

cheers.

**Comment by herrbischoff** [comment]
Thanks for the other links. I have checked them out and feel they are quite interesting. However, the one that stands out is DefleMask. A four-channel tracker! I haven't seen one of those since my early PC days (FastTracker) and still fondly remember NoiseTracker from my Amiga days. I cannot see a place on this list though. Maybe (probably) there's an Awesome List for audio applications out there which would no doubt benefit from your recommendations.

Reaper appears to be a cluttered mess compared to other commercial entries like Logic Audio and Cubase — both I have worked with professionally. I say that in the same way as Audacity compares to WaveLab or Mixx to Traktor. They are all without a doubt notable undertakings but simply cannot compare with the polish and feature set of their big brothers.

**Pull request closed without merging**
