### PR TITLE
Add OpenInTerminal

### PR DESCRIPTION
**Pull request by Camji55**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://github.com/Ji4n1ng/OpenInTerminal
2. [x] Why should this project be added: People seem to love it, and this will help it get to more people.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by onmyway133** [comment]
@Camji55 I made and added a simulator tool some years ago https://github.com/iCHAIT/awesome-macOS/pull/417, it was closed because the owner said it was too trivial

**Comment by iCHAIT** [comment]
@herrbischoff Do we close this?

**Comment by herrbischoff** [comment]
I'd say yes. However, given the popularity with such (in my view essentially useless) widgets and gizmos with junior developers, I feel someone else should decide. I will never have a use for an app that does what a one-line command can do

```
cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
```

I don't even use Finder to navigate code. At least this one is written in Swift.

**Comment by Camji55** [comment]
It's much more powerful than a simple script, and just because you don't use `Finder` when you code doesn't mean the 1,700 people who have starred the project don't 🤷‍♂

**Comment by Camji55** [comment]
I do appreciate, however, you leaving it up for endorsement!

**Comment by iCHAIT** [comment]
Closing due to lack of endorsement.

**Pull request closed without merging**
