### PR TITLE
Add Fork App

### PR DESCRIPTION
**Pull request by mavideniz**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://git-fork.com/
2. [x] Why should this project be added: It provides a very useful and free git interface.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
What exactly is "free" about this application? There appears to be a evaluation version but that's it.

**Comment by mavideniz** [comment]
All features of the application are completely free. If you only want to support the developers, you can support it for $49.99.

**Comment by iCHAIT** [comment]
I used this a few years back and personally loved it.  I am still not sure if it's free or not.  But, just from the software and usability point of view, it was awesome!

**Comment by stackptr** [comment]
I've been looking for an alternative to GitHub Desktop that exposes more of the Git feature set. After installing Fork, I like that stashes and tags are easier to view and that the commit history is more detailed. I also appreciate that a folder can be set to monitor git repos, which obviates my current workflow of cloning and then adding to GitHub Desktop.

I don't see any nagging messages to fork (heh) over money for the software in any of the usual places: preferences panels, toolbars, or on starting the app. If I'm not missing anything, I think the freeware icon should be added; or otherwise language added to state a purchase is not necessary to use the app.

If SourceTree is on the list, I don't see any reason this wouldn't be added as well. I wish it was open source but alas.

**Comment by iCHAIT** [comment]
@mavideniz Please resolve the merge conflicts and I'll merge!

**Comment by mavideniz** [comment]
> @mavideniz Please resolve the merge conflicts and I'll merge!

Solved!

**Pull request merged**
