### PR TITLE
Add Iconology

### PR DESCRIPTION
**Pull request by liamrosenfeld**
I corrected the issues you pointed out with my previous pull request by uploading a GitHub release for binary distribution and writing a new rationale that describes the full functionality of the program.

0. [ x ] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [ x ] Project URL: https://github.com/liamrosenfeld/Iconology
2. [ x ] Why should this project be added: It gives developers a method to quickly create icons from ~~glyphs~~ logos without the need to pay for any pro tools. It also integrates with Xcode (by automatically generating the import JSON) and can export additional filetypes (icns and ico) that many pro tools, such as Photoshop and illustrator, [do not support without additional scripts](https://forums.adobe.com/thread/2267956).
3. [ x ] End all descriptions with a full stop/period
4. [ x ] Entry is ordered alphabetically
5. [ x ] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
For me, this is decidedly not awesome.

1. It may be useful only for a *highly* specific task. Nothing wrong with that, but...
2. There's literally zero documentation or write-up. Just a GitHub repo with no proper README describing its purpose puts me off from even trying anything like it — every single time. And most important...
3. What does "quickly create icons from glyphs" even mean? WTF does it do at all, and why?

**Comment by liamrosenfeld** [comment]
@herrbischoff,
1. It does a highly specific task, but it is one that solo or small-team developers have to do quite often and is quite time-consuming when they have to.
2. The current README in the repo describes its full functionality in order to explain why you should download, and then the app itself explains the actual steps on how to use it. If you would like a more extensive README, I'd be happy to do so.
3. Glyphs are the logo that is featured inside of a full icon. This app allows you to import a glyph, make quick edits, then export it to a project in the necessary sizes with it autogenerating the necessary .json files (if needed for the selected preset).

**Comment by iCHAIT** [comment]
I don't think there should be an issue with point 1 above. An app may serve a highly specific task but if it works well and solves the problem at hand, it is good enough.

I have never really needed an app like this so I can't comment on its usefulness and can't really try it. Maybe people who need this and do this kind of stuff often can comment.

Let's merge this if it gets some endorsements.

@liamrosenfeld It would help if you can get some endorsements for the app :)

**Comment by liamrosenfeld** [comment]
@iCHAIT, sure thing. I'll try to get in touch with someone who starred the repo.

**Comment by NoahGold442** [comment]
Iconology has made changing my app icons so much easier. It used to take me an hour plus and a calculator but now it takes a few minutes and barely any thought at all.

**Comment by iCHAIT** [comment]
@liamrosenfeld Can you rebase your pull request? I'll merge it once Travis passes.

**Comment by herrbischoff** [comment]
@NoahGold442 So what you're saying is that it's clear to an iOS developer what this does — as is? Because I cannot make heads or tails of it and don't even understand its purpose. My hunch is (and my experience shows) that if doing something simple as changing an app icon (or even UI icons inside the app) takes over an hour with provided tools, you're probably doing something you should not be doing in the first place. It's very likely that I'm overlooking something but I'd like to understand what this is for, precisely. Because

> "Glyphs are the logo that is featured inside of a full icon."

is still the same contorted (and frankly non-sensical) description as before. In design (according to the designers I worked with), glyphs are symbols (or characters) like `A`, `b`, `ç` or `!`. A logo can be anything from a glyph to a complex multi-color illustration. An icon can be anything from a glyph to an abstract illustration.

@liamrosenfeld: Just to humor me: can you explain in plain, clear and succinct English what your software does precisely? @iCHAIT is about to merge it anyway, so this is just to help me understand.

**Comment by liamrosenfeld** [comment]
@herrbischoff, sorry I was confusing about glyphs. What I meant was the logo inside the icon. I should have used that phrasing from the start, and I'll use it from now on.

The flow of the app is:

When the user first opens the app, they are prompted to choose a file either with a file picker or a drag view.

Once they select a file, they are brought to a tweaking screen where they can make small changes like changing the background color, repositioning, scaling, and rounding the corners. 

The exporting of the app is abstracted into 'presets':
- The first set of presets is for Xcode. It contains iOS, iMessage, and MacOS. These save a JSON file alongside the images to allow for instant importing into Xcode.
- The second set of presets is files which allow you to export .icns and .ico files.
- The third set of presets is Iconsets which allow you to export both a MacOS Iconset and a Favicon Iconset.
- The final set is custom presets defined by the user. The user only has to provide a list of image sizes and the app will treat it like any other preset. That allows this app to match any workflow.

The tweaking screen automatically resizes to match the aspect ratio of the selected preset without stretching the original image.

**Comment by liamrosenfeld** [comment]
@iCHAIT, I rebased.

**Comment by liamrosenfeld** [comment]
Thank you!

**Pull request merged**
