### PR TITLE
Add MeetingBar

### PR DESCRIPTION
**Pull request by leits**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://meetingbar.onrender.com
2. [x] Why should this project be added: It's status bar app integrated with macOS calendar to show meetings and quick join.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
👍 from me. Great app. I personally have been using this for a while now. Works very well.

**Comment by dkhamsing** [comment]
Thx @leits @iCHAIT

**Comment by herrbischoff** [comment]
This is exactly what a small utility should be like: do one thing and do it well. Bonus points for making it FOSS. 🥇

**Comment by iCHAIT** [comment]
Yes, thanks for making this @leits and keeping it open source :)
This has been one of my favorite apps in recent times - lightweight, open-source, and most importantly does what it says.

**Comment by leits** [comment]
Wow. Thank you, @herrbischoff, @iCHAIT
I'm extremely pleased to hear this!

**Pull request merged**
