### PR TITLE
Add Postico (PostgreSQL client)

### PR DESCRIPTION
**Pull request by thechunk**
A good looking (paid with trial) PostgreSQL client.

### CODE REVIEW

**Comment by iCHAIT** [comment]
@herrbischoff  Thoughts on this?

**Comment by herrbischoff** [comment]
Difficult to say. This is the category of applications that need to be tested to get an impression. I'm really starting to get annoyed by App Store only apps.

**Comment by deizel** [comment]
Been using this for a while now and it does the job (admittedly I don't work with Postgres every day).

Not sure if "trial" is the word I would choose, more of a "lite" version since it doesn't run out:

> **What are the limitations of the free trial?**
>
> - At most 5 connection favorites
> - Only a single window per connection
> - Table filters are disabled
> - There is no time limit — use the trial as long as you want!

**Comment by dkhamsing** [comment]
@deizel 
can you rebase/fix the conflicts?

**Comment by dkhamsing** [comment]
let's close this at the end of the month if there is no activity

**Comment by vassyz** [comment]
This one should definitely be in. My reasons are:
* I use it quite often, it's the most user-friendly Postgres tool you can get on macOS. Not as feature-rich as [pgAdmin](https://www.pgadmin.org/), but far easier to use.
* The author can be trusted, he already has a tool in the awesome-macOS list: [Postgres.app](http://postgresapp.com/)
* [PSequel](http://www.psequel.com/), the only Postgres GUI app mentioned here, is not as good as Postico, although it's free
* Postico can be used for free if you don't need more than five connections and don't have to use two connections side by side. Filters can be applied manually by writing the queries.

**Comment by dkhamsing** [comment]
@vassyz thanks!

**Comment by dkhamsing** [comment]
@thechunk can u rebase?

**Pull request closed without merging**
