### PR TITLE
Add Telegram proMacOS ru

### PR DESCRIPTION
**Pull request by LestaD**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Nice try spamming the list. Goodbye.

**Comment by LestaD** [comment]
@herrbischoff spamming?! Really?

**Comment by LestaD** [comment]
@herrbischoff does you open that group before close pr?

**Comment by LestaD** [comment]
https://t.me === https://telegram.me

**Comment by LestaD** [comment]
@iCHAIT

**Comment by herrbischoff** [comment]
Adding a random chat group behind a URL shortener without any explanation as to why is considered spamming in my book. Maybe you should have followed the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md) as well as the [Pull Request Template](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/PULL_REQUEST_TEMPLATE.md), laying out your reasons for suggesting it in detail instead of deleting it wholesale. Especially when adding a non-English resource on a messenger platform you need to have an account on to even see anything. Additionally you should have realized that your suggestion is the first one in a language other than English. Asking about that in an issue would have helped as well, demonstrating you thought about what you're doing before doing it.

**Comment by LestaD** [comment]
t.me is not url shortener

**Comment by LestaD** [comment]
Thanks for full answer

**Comment by herrbischoff** [comment]
Feel free to edit this pull request or open a new one with detailed information and we can discuss a possible addition within the team.

**Pull request closed without merging**
