### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by crash-bash**
Add "macOS 10.15 Catalina Setup" section.

### CODE REVIEW

**Comment by iCHAIT** [comment]
@herrbischoff I'll leave this up to you for review :)

**Comment by iCHAIT** [comment]
@herrbischoff Did you get a chance to look at this?

**Comment by iCHAIT** [comment]
LGTM.

Thanks @crash-bash

**Comment by herrbischoff** [comment]
Didn't get a chance to review it. It's probably fine, although I'm generally not a fan of such setup guides.

**Pull request merged**
