### PR TITLE
Add Rocket to Productvity

### PR DESCRIPTION
**Pull request by vikrantnegi**
0. [x] Project URL: http://matthewpalmer.net/rocket/
1. [x] Why should this project be added: Makes adding emojis faster while typing even where they are no tool to add emojis. You can blacklist app where you don't want emoji suggestions like editors.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by iCHAIT** [comment]
I really like this. I tried it out as well and it works really well.

The only concern I could see is that it does not work on all applications, and I believe for some applications it does not work on purpose (for instance on code editors like Sublime Text), and other applications may not be supported. But it worked on most, and I like it.

👍  from me.

@herrbischoff @dkhamsing what do you think?

**Comment by vikrantnegi** [comment]
@iCHAIT Yeah, I really like this and yes you can filter out apps that you don't want emoji's suggestions. I got to know about this from [Wes Bos](http://wesbos.com/uses) personal site. He uses it on his videos tutorials.

**Comment by dkhamsing** [comment]
Looks good! Merging

**Comment by herrbischoff** [comment]
OMG, emojis! Now we can all text like teenage girls, all the time! ❤️ 😍 😻 ❤️ 😍 😻 ❤️ 😍 😻 ❤️

Sorry, but I don't get this emoji thing. :P

**Pull request merged**
