### PR TITLE
Added macchanger

### PR DESCRIPTION
**Pull request by shilch**
Hi,
as I told in #317 the [macchanger](https://github.com/acrogenesis/macchanger) provided in the list did not work for me and I made [one](https://github.com/shilch/macchanger) which works.
Maybe it helps other people facing the same problem.

### CODE REVIEW

**Comment by dkhamsing** [comment]
can you rebase/fix the conflicts?

**Comment by shilch** [comment]
I do not know why there are conflicts. Travis-ci.org tells me that [this repository does not exist ](https://travis-ci.org/iCHAIT/awesome-osx/builds/141628573)

**Comment by dkhamsing** [comment]
@shilch if it makes it easier, you can also open a new pull request from https://github.com/iCHAIT/awesome-macOS

**Comment by shilch** [comment]
I think you have to trigger a build? I can't do this

**Comment by dkhamsing** [comment]
@shilch your fork has diverged from this repo so you have to rebase
try this https://help.github.com/articles/about-git-rebase/

**Comment by iCHAIT** [comment]
@dkhamsing I also think that I turned off travis CI for the repo a while back, can you take a look and re enable it?

**Comment by dkhamsing** [comment]
@iCHAIT travis ci settings are only available to you.. 

what does it look like when u go to
https://travis-ci.org/iCHAIT/awesome-macOS/settings

**Comment by iCHAIT** [comment]
Oh I see, here is what it looks like - https://i.imgur.com/zj9AVnl.png

**Comment by shilch** [comment]
Ok, I opened a new pull request #319

**Comment by dkhamsing** [comment]
@iCHAIT ci issue will be continued on #332

**Pull request closed without merging**
