### PR TITLE
Add Code of Conduct document

### PR DESCRIPTION
**Pull request by herrbischoff**
In light of recent events, I feel it is proper to add a basic Code of Conduct document. I'd really rather not because — at least for me — all of the points are basically a given but unfortunately there are a bunch of people out there ruining things for others.

I don't think a document in and of itself will change anything but at least there's a more or less clear guideline to what amounts to acceptable behavior.

Let me know what you think.

### CODE REVIEW

**Comment by dkhamsing** [comment]
Can we add it to .github folder and use CODE_OF_CONDUCT.md 

https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by herrbischoff** [comment]
Good catch, didn't see that before. I will change that tomorrow.

**Comment by iCHAIT** [comment]
👍

**Comment by iCHAIT** [comment]
And maybe it would be useful to add a link to Code of Conduct somewhere in the Readme as well?

**Comment by herrbischoff** [comment]
Absolutely. I'll look into everything today.

**Comment by dkhamsing** [comment]
Thank you

**Pull request merged**
