### PR TITLE
Add SlowQuitApps

### PR DESCRIPTION
**Pull request by dteoh**
It is an open source alternative to CommandQ.

### CODE REVIEW

**Comment by dkhamsing** [comment]
not sure about this one.. can anyone else comment?

**Comment by herrbischoff** [comment]
For people with fast keyboard refresh rates (like me), I see the potential of inadvertently closing a whole bunch of applications at once by holding `Cmd-Q` instead of tapping it.

**Comment by dkhamsing** [comment]
can you rebase/fix the conflicts?
@dteoh

**Comment by dteoh** [comment]
Thanks, commits rebased.

**Comment by dkhamsing** [comment]
thx!

**Pull request merged**
