### PR TITLE
Non-native

### PR DESCRIPTION
**Pull request by herrbischoff**
This pull request removes all applications that are not truly native macOS applications.

### CODE REVIEW

**Comment by knpwrs** [comment]
This list is gonna get so small!

**Comment by knpwrs** [comment]
Probably for the best though. I originally started watching this list for cool things I could do with my Mac that weren't web apps.

**Comment by herrbischoff** [comment]
Same here. I'm always for quality over quantity, even if the list shrinks. Speaking of quantity: do we really need three different apps on this list for keeping your Mac "awake"?

**Comment by knpwrs** [comment]
I personally use Amphetamine. When you said there were three on this list I was surprised I didn't see [Caffeine](http://lightheadsw.com/caffeine/) anywhere.

**Comment by knpwrs** [comment]
uh-oh...

image

**Comment by herrbischoff** [comment]
Personally I have never needed this kind of application, they are gizmos to me. Should I ever need to keep my Mac awake, I change Energy Settings or just run `caffeinate -u -t 3600` in the shell.

**Comment by iCHAIT** [comment]
@herrbischoff :+1:

**Comment by herrbischoff** [comment]
Alright, I'm going to push the big scary button, merging these deletions in.

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
