### PR TITLE
Add mas.

### PR DESCRIPTION
**Pull request by knpwrs**
0. [x] Project URL: https://github.com/mas-cli/mas
1. [x] Why should this project be added: Consider [this script](https://github.com/knpwrs/dotfiles/blob/e4d3addc0cf64998eb9c199d01c8d864562dcf7e/vendor/packages/install-mas.sh) which is a part of my dotfiles install. I can very quickly get a new Mac set up barely having to touch a thing.
2. [x] End all descriptions with a full stop/period
3. [x] Entry is ordered alphabetically
4. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for your addition. However, as it is a shell application, I feel it would be better suited for a list like https://github.com/herrbischoff/awesome-command-line-apps.

@iCHAIT, @dkhamsing: thoughts?

**Comment by knpwrs** [comment]
Or even https://github.com/herrbischoff/awesome-osx-command-line. I still think it's a good fit here though because it can be used to install many of the apps listed.

**Comment by herrbischoff** [comment]
@knpwrs: True. Now I'm unsure. :) Let's see what the others say.

**Comment by dkhamsing** [comment]
my vote is to go to command line list

**Comment by herrbischoff** [comment]
Since we have https://github.com/iCHAIT/awesome-macOS#command-line-utilities and already entries like `m-cli` and `Mac-CLI`, we should decide if we want to keep this section. If we do keep it, I feel `mas` would be a proper addition.

**Comment by dkhamsing** [comment]
the command line section should point to https://github.com/herrbischoff/awesome-command-line-apps and related lists

**Comment by iCHAIT** [comment]
@herrbischoff I don't think we should remove that section, its a quick way to get to cool resources related the command line . 

> the command line section should point to https://github.com/herrbischoff/awesome-command-line-apps and related lists

I think that section already points to this list :)

Lets just add mas to that section.

**Comment by iCHAIT** [comment]
@knpwrs 

The OSS icon should also point to the github repository.

`[![Open-Source Software][OSS Icon]](https://github.com/mas-cli/mas)`

**Comment by iCHAIT** [comment]
And target your suggestion at https://github.com/iCHAIT/awesome-macOS#command-line-utilities

**Comment by knpwrs** [comment]
All set.

**Comment by iCHAIT** [comment]
👍

**Pull request merged**
