### PR TITLE
CI Test

### PR DESCRIPTION
**Pull request by dkhamsing**
testing ci..

DO NOT MERGE

### CODE REVIEW

**Comment by dkhamsing** [comment]
@iCHAIT looks like ci is broken.. may have been something with changing the repo name

Couple of things we could try but you have to do it as the owner

1. Reset the project with travis to https://travis-ci.org/profile/iCHAIT (turn the switch off and on) or
2. Use circleci (I find they are faster) https://circleci.com/

Let me know what you decide

**Comment by iCHAIT** [comment]
> Reset the project with travis to https://travis-ci.org/profile/iCHAIT (turn the switch off and on) or

tried but doesn't work :/

**Comment by iCHAIT** [comment]
I think you need to push something to trigger a build

**Comment by iCHAIT** [comment]
Fingers crossed

**Comment by dkhamsing** [comment]
Looks like it's back on

**Comment by dkhamsing** [comment]
yo you're up late!

**Comment by dkhamsing** [comment]
@iCHAIT took a while but the builds ran
will be fixing those issues found

closing

**Pull request closed without merging**
