### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yuqingcai**
Add Cymbols app info.

0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://cymbols.io/
2. [x] Why should this project be added: Cymbols help programmers to understand code efficiently.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
This is something every decent IDE has built-in. Using an external app for this is a nice programming example and would possibly of small interest if it were FOSS. Wanting to charge $60+ for it squarely puts this in the "no" camp for me.

@dkhamsing, @iCHAIT: what do you think?

**Comment by yuqingcai** [comment]
@herrbischoff, thanks for your comment :-)
Cymbols supported multiple languages (even ASM)  and handle large project (such as Linux contain 10000+ files) to make the quick symbol search, it is a powerful source analyzer.

**Comment by iCHAIT** [comment]
I am neutral on this!

**Comment by iCHAIT** [comment]
Although, it is definitely too pricy for what it does!

**Comment by yuqingcai** [comment]
Do you hear about "Source Insight"? (https://www.sourceinsight.com/)
It is software under windows that does the same thing.
OK, let's go further talk about Cymbols. If it has more abilities such as autocomplete, quick jump, etc like a modern text editor, would you like to use it? And what price is acceptable for you? As its author, I need the comments, if you have some good suggestions, please let me know. :-)
@herrbischoff @iCHAIT

**Comment by dkhamsing** [comment]
Will side with @herrbischoff

**Pull request closed without merging**
