### PR TITLE
Remove Electron wrapper apps

### PR DESCRIPTION
**Pull request by herrbischoff**
To discuss the merits of those applications despite the fact that they are basically web apps.

Seeing the final list of removals, I'd vote to just merge the whole PR, thereby extinguishing all traces of Electron and Chromium wrappers. Contrary to my former statement that Atom should be included, I feel that the performance gain alone of native apps like Sublime Text or even Vim justify that. In my view, none of the apps in this pull request are outstanding applications without equal or better native alternatives. Case in point: Caret vs. Typora, Atom vs. Sublime Text.

Still, I'm quite surprised to see practically all so-called "modern" editors are built using Electron. I understand the popularity and appeal. However, on a **macOS** awesome list, none of those should have a place.

Having said that, I would of course be open to also remove any cross-platform applications with no clean implementation of the Apple Human Interface Guidelines, meaning: which may be free but look like crap.

### CODE REVIEW

**Comment by knpwrs** [comment]
FWIW, this won't automatically apply to all Electron apps in the future. I'm currently working on an Electron app that uses native macOS APIs -- Electron is just providing the user interface.

**Comment by herrbischoff** [comment]
@knpwrs: This is a good contribution to the discussion. As the base assumption here is to judge the applications based on merit (despite my own views), this is very likely to happen. I don't like those apps as I prefer to use snappy, native and consistent applications. The current fad of app-ifying everything does not sit right with me as the create-once-run-everywhere fad did years before. The best experience was, is and will always be a native application with familiar UI elements for the respective platform, be it macOS, iOS, Android, Windows, Linux (well...), whatever. There's a reason Apple dropped skeudomorphism in favour of a clean, elegant and meaningful UI. My view about UI appears to be quite at odds with yours — for me, there is no such thing as "just the user interface". As far as the user is concerned, *the interface* is *the application*.

**Comment by iCHAIT** [comment]
@dkhamsing @dufferzafar Your thoughts?

**Comment by knpwrs** [comment]
@herrbischoff Just curious, what would you say about applications such as Audacity or Blender (both on this list)? Audacity is WX, so it uses native widgets, but it hardly fits in with other apps (visually). Blender uses its own UI toolkit and AFAIK doesn't implement any macOS-specific functionality.

**Comment by dufferzafar** [comment]
Considering this list is for macOS, I agree with @herrbischoff :+1:

**Comment by akz92** [comment]
I don't think that this should be a list of the apps that have the most Apple-like UI and UX. In my opinion this should be a list of the best software available for the platform. To use text editors as an example, yes Sublime is native and performs better than Atom but Atom is still a good text editor and as such should have it's place on this list. The same applies to a bunch of 'Electron wrapper apps'. 

I believe that there's a difference between web-apps wrapped as a desktop app (Slack i.e.) and apps built on Electron (Atom i.e.).

**Comment by knpwrs** [comment]
@akz92 You could argue that Slack actually does use native features not available in the web app. Two examples:

1. You can close the window and still get notifications and messages and whatnot.
2. The Electron app uses notification features that aren't available in web notifications, e.g., being able to reply directly in a notification.

Other than that, yeah, Slack is primarily a web app -- it functions almost the same in a browser whereas Atom will not function outside of Electron.

**Comment by iCHAIT** [comment]
@herrbischoff Since you have got a +1 from one of the list maintainers (@dufferzafar), feel free to merge this PR, though you may want to add a line about the policy that we are going to follow for electron wrapped apps in `contributing.md` so that its a bit easier for us to reject a PR for such apps in the future and settle this argument one and for all.

**Comment by vassyz** [comment]
Atom is slow, but for me it's the best editor I can get on macOS, and I've tried them all. Also Slack has got a huge thumbs up from the tech community. I agree with not having web-wrappers in this list, but banning software just because it uses a certain technology seems a bit extreme.

**Comment by dkhamsing** [comment]
Of all these, I actually use Atom and Slack so I would vote to keep em 😅

Can't quite articulate why though.. just habit?

- Atom is visually very pleasing and fast enough for my use
- Slack works great and I believe the app has more native shortcuts vs the web version

**Comment by lordgiotto** [comment]
I'm really sad about this PR :(
Any app should, in my opinion, be judged on it's quality and features, not on the technology behind its implementation. The technology is only the tool, but are shape and functionality that make an app awesome.
My 2 cents ;)

**Comment by dkhamsing** [comment]
should we put this to a vote, whats the status

**Comment by knpwrs** [comment]
_My_ opinion:

There is an [Awesome Electron](https://github.com/sindresorhus/awesome-electron) list. Things on this list would be best to show a specific strength of macOS. But that doesn't only apply to Electron Apps -- as I've mentioned earlier, Audacity and Blender on are this list but hardly show off anything about the platform or fit in with the rest of macOS. Those (and a number of Electron apps) would probably be better off on an Awesome Crossplatform list.

Maybe another section (or even another file) in this same repository would be appropriate? Awesome stuff that is available on macOS that isn't specifically awesome because of macOS?

**Comment by iCHAIT** [comment]
@knpwrs Thanks for the idea mate.

@herrbischoff @dkhamsing Merging this, and for future lets encourage contributors to target their electron wrapped software suggestions to awesome electron list rather than platform specific one.

**Comment by knpwrs** [comment]
@iCHAIT What would you say about the latter part of my comment? Non-Electron apps that aren't really great fits for the macOS ecosystem?

**Comment by iCHAIT** [comment]
@knpwrs 

> Awesome stuff that is available on macOS that isn't specifically awesome because of macOS

I am not entirely sure to be honest, I think it is inevitable that such apps should fall in a some awesome list because they **are awesome** at the end of the day, maybe/maybe not this list.

Though, I don't think having a separate section for such apps in this list itself would harm anyone,

What say @herrbischoff @dkhamsing ?

**Comment by dkhamsing** [comment]
Seems simpler for now to not allow Electron apps

If we have missed any, feel free to open a pull request

**Comment by knpwrs** [comment]
I was more referring to things like Blender or Audacity. Do they belong on this list?

**Comment by dkhamsing** [comment]
@herrbischoff can you take a look

**Comment by iCHAIT** [comment]
@knpwrs I would suggest you to open a PR removing them so that it is more easier to scrutinize :)

**Comment by herrbischoff** [comment]
@dkhamsing: I will check them out.

**Comment by herrbischoff** [comment]
Please see #372.

**Comment by hzb** [comment]
Forked -> Add something -> Submitted a PR -> Read the document `contributing.md` -> Cancelled submission and Deleted the forked repo.

This is my process of contributing to this repo.

**Pull request merged**
