### PR TITLE
Added GifCapture

### PR DESCRIPTION
**Pull request by dmlemos**
0. [x] Project URL: https://github.com/onmyway133/GifCapture
1. [X] Why should this project be added: It is a great open-source tool to make GIFs. Does not depend on any external service, which is a big advantage (comparing to the likes of GIPHY). There are not many choices on standalone apps for this kind of job.
2. [X] End all descriptions with a full stop/period
3. [X] Entry is ordered alphabetically
4. [X] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by dmlemos** [comment]
This project has no homepage, so I had to remove the OSS link to avoid URL duplication

**Comment by dmlemos** [comment]
So the CI errors have nothing to do with my change 🙁 

Please confirm

**Comment by iCHAIT** [comment]
Looks good to me :)

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
