### PR TITLE
Add eul.im chat client to chat list

### PR DESCRIPTION
**Pull request by JadoJodo**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://eul.im/
2. [x] Why should this project be added: It's a great client that is under active development and supports a lot of surprising clients, including: Telegram, Discord, WhatsApp, etc
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
I’m gonna go out on a limb here and assume this is an Electron app. Please READ the contribution guidelines. I don’t know how to make that any clearer.

**Comment by JadoJodo** [comment]
@herrbischoff 

I did read the the contribution guide. 

I don't believe this is an Electron app. The website's description of "Light
eul is a native desktop app that weighs only a couple of megabytes and has minimal CPU and RAM usage." would suggest it is not, as Electron has neither minimal CPU or RAM usage.

**Comment by herrbischoff** [comment]
I’m going to investigate it further tomorrow. Sadly, many authors claim “native” for Electron apps.

**Comment by stackptr** [comment]
Doesn't seem to be Electron. I tried it out just now, it starts up with downloading a "minimal browser" for authentication purposes. Investigating the package contents just shows a single binary, versus other known Electron apps including `Electron Framework.framework` and `electron.asar` (among others).

Unfortunately the app itself is quite barebones and comparable more to an IRC client. It also crashed a few times when I was poking around. Doesn't seem like it would fit in with other apps in this repo, in my opinion...

**Comment by herrbischoff** [comment]
@stackptr: Thanks for letting us know! Especially the crashing part is skewing my opinion towards waiting for a later version. I'm going to flag it as "revisit later". Thanks anyway, @JadoJodo!

**Pull request closed without merging**
