### PR TITLE
Added CleanMyMac

### PR DESCRIPTION
**Pull request by highvoltag3**
Added clean my mac utility been using this for years since it’s first
version and I think it’s does what it states really well.

### CODE REVIEW

**Comment by iCHAIT** [comment]
@herrbischoff Why a 👎 ? I actually used it a while back and found it pretty reasonable.

**Comment by dkhamsing** [comment]
can you rebase/fix the conflicts?

**Comment by herrbischoff** [comment]
IMHO, all commercial "cleaning" and "optimization" tools are a rip-off because macOS runs most maintenance tasks itself. Besides, any person who is reasonably proficient with GitHub should be proficient enough with their OS to not feel the need for such snake oil. This isn't Windows country after all.

**Comment by dkhamsing** [comment]
I think I agree with @herrbischoff 
Closing

**Pull request closed without merging**
