### PR TITLE
Add Reminders Menu Bar

### PR DESCRIPTION
**Pull request by DamascenoRafael**
0. [x] I have read the [Contribution Guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md)
1. [x] Project URL: https://github.com/DamascenoRafael/reminders-menubar
2. [x] Why should this project be added: Reminders Menu Bar lets you interact with reminders directly from the menu bar without having to open Apple Reminders. Allowing quick access to view, create or edit reminders that will be in sync with Apple Reminders.
3. [x] End all descriptions with a full stop/period
4. [x] Entry is ordered alphabetically
5. [x] Appropriate icon(s) added if applicable (OSS, freeware)

### CODE REVIEW

**Comment by herrbischoff** [comment]
Looks quite nice. However, its Dark Mode color scheme is off and appears to not been properly implemented. As soon as that is working as expected, I see this as a candidate for inclusion.

**Comment by DamascenoRafael** [comment]
Hey @herrbischoff, thanks for your comment. Could you report what behavior you had in dark mode?

**Comment by herrbischoff** [comment]
Just realized that this is probably due to my "Increase Contrast" accessibility setting. Opened a bug report: https://github.com/DamascenoRafael/reminders-menubar/issues/34

**Comment by iCHAIT** [comment]
👍  from me

**Comment by herrbischoff** [comment]
@DamascenoRafael Hey, any news on my bug report? I'm going to merge this as soon as it is resolved.

**Comment by herrbischoff** [comment]
Any news on this issue yet? It's been two months now. Not exactly my definition of "awesome".

**Pull request closed without merging**
